### ISSUE TITLE
Reconfirmable not setting unconfirmed_email

### ISSUE THREAD

**Issue by grdmnt** [graphql-devise/graphql_devise#102]
### Describe the bug

So I have `Devise.reconfirmable` set to true and have the `user.unconfirmed_email` attribute. I've tried updating an email of a confirmed user and it doesn't set the `unconfirmed_email` attribute. I thought that this might be a compatibility issue with some gem, but I tried this on a fresh rails app with only `graphql_devise` installed and the issue still persists. 

I thought that maybe I'm just doing this wrong and tried it on a fresh rails app, but this time with the `devise` gem only. Tried it again here, and it worked.

Is this a known issue?

I'm using Rails 6.0.3 and Ruby 2.6.6

### Steps to reproduce

1. Create a user
2. Confirm the user
3. Update the user's email
4. The user.unconfirmed_email should be nil
### Expected behavior

The user.unconfirmed_email should have the new email 

### Actual behavior

The user.unconfirmed_email returned nil

**Comment by grdmnt** [comment]
Checked where devise puts the old email into `unconfirmed_email` and it led me to this line in devise:
https://github.com/heartcombo/devise/blob/fee43f3c11e176c53c5c3bfda7fd2e97c4c912be/lib/devise/models/confirmable.rb#L58

Tried to debug it by adding this into my user model.
```
def postpone_email_change?
    result = super
    binding.pry
    result
  end
```
Tried checking the condition and this specific line is making this conditional false

https://github.com/heartcombo/devise/blob/fee43f3c11e176c53c5c3bfda7fd2e97c4c912be/lib/devise/models/confirmable.rb#L282

<img width="678" alt="Screen Shot 2020-06-14 at 2 50 53 AM" src="https://user-images.githubusercontent.com/10776105/84576773-de7de800-ade9-11ea-835d-c95c6957bba5.png">

**Comment by mcelicalderon** [comment]
Hey @grdmnt. Yes, this is a known issue with devise token auth. Their model concern overrides a method that breaks this. Y made it work on a project and will post what I did, here, later. But maybe this is something we can fix in this gem. I'll take a look into implementing a fix for this.

**Comment by grdmnt** [comment]
Got back from a bit of digging. The new DTA version (1.1.4) released this month includes this fix:
https://github.com/lynndylanhurley/devise_token_auth/pull/1343

So after putting this line in the `devise_token_auth` intializer: `config.send_confirmation_email = true`, everything worked. Make sure to have `config.default_confirm_success_url` set as well though.

**Comment by mcelicalderon** [comment]
Really? That's awesome! I'm glad they fixed it. Thank you for looking into that.

**Comment by mcelicalderon** [comment]
Closing this one as this is fixed by upgrading to devise_token_auth to v1.1.4

**Comment by grdmnt** [comment]
I think we have to open this back up since when we add set `config.send_confirmation_email` to true, it uses the confirmation email template from DTA instead of the one given in this gem.

**Comment by mcelicalderon** [comment]
Oh no, thank you for trying all of this out. I can take a look at it later. In the mean time, you can just replace the mailer with your own in the devise directory as I guess that's the one the method is using

**Comment by grdmnt** [comment]
Yep! I'm currently just copying the mailer template given in this gem. I'll update this issue if I get problems with it.

**Comment by grdmnt** [comment]
Figured out how to make things work for reconfirmable.

```
# TODO: Should be removed in a new update in DTA
  # https://github.com/lynndylanhurley/devise_token_auth/issues/1374
  def sync_uid
    if persisted? && devise_modules.include?(:confirmable) && !@bypass_confirmation_postpone
      return if postpone_email_change?
    end

    self.uid = email if email_provider?
  end

  def send_reconfirmation_instructions
    # This needs to be loaded before attempting to send an email to have the devise mappings
    # set properly
    ApiSchema

    @reconfirmation_required = false

    return if @skip_confirmation_notification

    send_confirmation_instructions(
      redirect_url: <redirect_url>,
      template_path: ['graphql_devise/mailer'],
      controller: 'graphql',
      action: 'execute'
    )
  end
```

Added these in my devise model. Take note that the ApiSchema is being preloaded before sending since when I try to update in console, it fails since the devise mappings are not yet loaded, given that the resource loaders aren't called yet at that point in console.

I'll be testing this out more and see if there are edge cases still. I'll update this thread if something comes up.

**Comment by mcelicalderon** [comment]
Hey @grdmnt! Thank you for looking into that. Yeah, now I remember the sync uid thing was a problem. I remember fixing that not in the best way, I bet your solution is better.

But after giving this fix a try on #109 I realized that the level of complexity for this goes 3 levels deep as most of the implementation is in Devise. So, we concluded that the best way to fix this is by providing our own method to the model. This way we won't depend on dta fixing it or devise breaking it for dta. I already started working on this, so I would expect to have it ready next week

**Comment by grdmnt** [comment]
That would be a nice addition. Now that you mentioned that, you're right, there's a big chance that my workaround would easily get broken when DTA or Devise starts to do something different about these. I hope it doesn't break soon HAHA. Looking forward for the new feature! Thanks man!

**Comment by mcelicalderon** [comment]
So #111 fixed this by providing a new mechanism to reconfirm emails (using a new model method). This idea comes from something that already exists on devise, a method called `update_with_password` which will check for the presence and validity of current password before allowing a password update. So what I think is missing is a third update method that combines both password and email confirmation updates, so the user can choose what kind of update they want to perform.
