### ISSUE TITLE
Devise mapping error

### ISSUE THREAD

**Issue by pelarejo** [graphql-devise/graphql_devise#103]
### Describe the bug

Hi,
I've been trying to install `graphql_devise` in a rails API app.
After initializing the gem to be mounted in the schema,
the before_action in graphql_controller `set_resource_by_token(:user)` fails with:

```NoMethodError (undefined method `to' for nil:NilClass)```

I suspect a failure in mounting devise or I misunderstood something.

### Environment

Gemfile:
https://github.com/pelarejo/gql_devise_error_demo/blob/master/Gemfile

Gemfile.lock:
https://github.com/pelarejo/gql_devise_error_demo/blob/master/Gemfile.lock

### Steps to reproduce

I have installed the gem as describe in the demo project's README.
Start the rails server and fetch the schema or launch the `userLogin` mutation.

More details below.

### Expected behavior

I exepected to be able to login straight away.

Digging a little, this error comes from `Devise.mappings` being *empty* during `devise_token_auth#resource_class` after the controller  execute `set_resource_by_token(:user)`

I expected the `GraphqlDevise::ResourceLoader` in the schema added through the generator to programatically mount the devise module. Isn't that why it's for ?

### Actual behavior

The graphql_controller `set_resource_by_token` call fails with:
```NoMethodError (undefined method `to' for nil:NilClass)```

Here is the graphql stacktrace:
https://gist.github.com/pelarejo/4a3f9d58898ead574bf1552ae4ba331a

### Reproducible demo

Clone this repo:
https://github.com/pelarejo/gql_devise_error_demo

Start the server:
```
$ bundle
$ rails db:migrate
$ rails server
```
Launch the query:
```
curl --request POST \
  --url http://localhost:3000/graphql \
  --header 'content-type: application/json' \
  --data '{"query":"mutation userLogin($email: String!, $password: String!) {\n  userLogin(email: $email, password: $password) {\n    credentials {\n      client\n      accessToken\n      expiry\n      tokenType\n      uid\n    }\n  }\n}","variables":{"email":"user@example.com","password":"password123"},"operationName":"userLogin"}'
```

**Comment by 00dav00** [comment]
Hey @pelarejo, [your controller](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/app/controllers/api/v1/graphql_controller.rb#L4) seems to be missing the concern gem concern. Please take a look at the [dummy project controller](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/app/controllers/api/v1/graphql_controller.rb#L4) as an example. 

Do you remember what options you when executing the generator?

**Comment by pelarejo** [comment]
> Hey @pelarejo, [your controller](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/app/controllers/api/v1/graphql_controller.rb#L4) seems to be missing the concern gem concern. Please take a look at the [dummy project controller](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/app/controllers/api/v1/graphql_controller.rb#L4) as an example.
> 
> Do you remember what options you when executing the generator?

Hi @00dav00,

The generator adds the `GraphqlDevise::Concerns::SetUserByToken` concern in the [ApplicationController](https://github.com/pelarejo/gql_devise_error_demo/blob/master/app/controllers/application_controller.rb) by itself. Does it not work through inheritance ?

I have written all steps required to create the project in its README. Here is the generator line:
```
$ rails generate graphql_devise:install User --mount TestAppSchema
```

**Comment by mcelicalderon** [comment]
Hey @pelarejo ! Thank you for providing a repo with the error. I'll take a look into this ASAP.

**Comment by mcelicalderon** [comment]
Ok, I figured it out and you are right, @pelarejo 🤦 . This is a problem with eager_loading. Works fine in production environments, but you will have this problem in any env that has eager_loading disabled. In the mean time you can fix it by just enabling that and I will figure out a way to fix this ASAP.

**Comment by pelarejo** [comment]
Hey @mcelicalderon,

I suspected something as such, I'll do the temporary fix you suggested.  
I wish I could help out but my understanding of rails' eager_loading is too limited.

Thank you very much for the very fast updates, the recent changes introduced in v0.12 are amazing. Keep it up !

**Comment by mcelicalderon** [comment]
You are welcome! And just to provide a better understanding of what's going on, you don't even need to enable eager loading in the entire app, that's just one way to make sure your `TestAppSchema ` class is loaded by Rails before a request happens. So, just calling your class (TestAppSchema) anywhere in your code (maybe an initializer) will fix the problem

**Comment by mcelicalderon** [comment]
Rails autoload is crazy 😱 so don't try the initializer thing, it won't work. Eager loading does work, but #107 takes care of this

**Comment by pelarejo** [comment]
I know right ! I decided to call my schema in the `before_action` instead, it seems to work fine.

I've taken a look at #107, it's not bad at all ! A bit of a shame to make the use of `graphql_context` a requirement but I expect most people will use it anyway.

**Comment by mcelicalderon** [comment]
In the end I think it is even better to force the use of the method. That way we can change things with the gem without having users to modify it across versions. And of course you can merge anything else you need to that the returned hash of the method. It will always be a hash.

**Comment by mcelicalderon** [comment]
Just wanted to be clear on the fact that using the method `graphql_context` is not really a requirement, but just recommended. As long as you understand what the method returns (might change across versions) you can build the hash yourself. For the current version, this 2 are equal:
``` ruby
# In your graphql controller

# Using the method
render json: YourSchema.execute(
  params[:query],
  context: graphql_context(:user).merge(any: 'other value for the context'),
  variables: params[:variables]
)

# Doing it manually
render json: YourSchema.execute(
  params[:query],
  context: { controller: self, resource_name: :user, any: 'other value for the context' },
  variables: params[:variables]
)

**Comment by pelarejo** [comment]
Thanks for the clarification, I've already updated the gem, everything works as expected.
Cheers !
