### ISSUE TITLE
Checking for `performed?` when mounting into your graphql schema.

### ISSUE THREAD

**Issue by grdmnt** [graphql-devise/graphql_devise#110]
### What is the problem the enhancement will solve?

I saw that in this gem's codebase that the controller checks for `performed?` since `confirmAccount` and `checkPasswordToken` calls `redirect_to` to the given redirectUrl or the default redirect url. Since by default, the `graphql-ruby` gem does not have this `performed?` check in the default graphql controller, this might look like a bug for `graphql_devise` and developers wouldn't know where that double rendering issue is being invoked unless they check `graphql_devise`'s codebase.

### Describe the solution you have in mind

I think it's worth noting in the documentation, around in this [area](https://github.com/graphql-devise/graphql_devise#queries), that when you mount this gem into your own graphql schema, that they should check for `performed?` inside their graphql controller before rendering the result since there are operations in the gem that uses `controller.redirects_to`

**Comment by mcelicalderon** [comment]
You are absolutely right, and I bet there are a couple of things that will keep coming up when you mount this on your own schema. And yes, for this not sure there is something else we can do but document it. We also need to add more tests on the mount in your app schema part, probably all the ones we have for the separate route.

Thanks for the report!

**Comment by 00dav00** [comment]
@grdmnt Just updated the readme to include this info:
https://github.com/graphql-devise/graphql_devise#authenticate-before-reaching-your-gql-schema

Closing this one for now.
