### ISSUE TITLE
How to get user data on login?

### ISSUE THREAD

**Issue by ThiagoCasao** [graphql-devise/graphql_devise#116]
### Question

I need to get user info when the user log in, but I dont want to call GraphQL server again.
So, I see on [https://github.com/graphql-devise/graphql_devise/blob/master/spec/requests/mutations/login_spec.rb#L20](url) that the userLogin mutation can return user info, but when I try:
`curl http://localhost:3001/graphql -H 'Content-Type: application/json' -d '{ "query": "mutation { userLogin( email: \"user@gmail.com\", password: \"123456\") { user { id email }, credentials { uid accessToken client expiry } } }" }'
`
I receive following message:
**{"errors":[{"message":"Field 'user' doesn't exist on type 'UserLoginPayload'"**

What is the right way to get that info? Another call to server?

Thank you.

**Comment by mcelicalderon** [comment]
Hey @ThiagoCasao ! So, by default most mutations have another field called `authenticatable` and this includes the login mutation, so you could do
```graphql
mutation {
  userLogin(email: "user@gmail.com", password: "123456") {
    credentials { uid accessToken client expiry }
    authenticatable { id email }
  }
}
```
Of course you need to take into account the fact that the gem will try to use in this case a type you should define `Types::UserType` in your project. If this type is not defined by you, the gem will use a generic type `AuthenticatableType` which only contains an `email` field. Let me know if that helps. I highly recommend you make use of instrospections queries in GraphQL to better understand the schema that you are defining. There are many ways out there, but I personally have this on my projects https://github.com/rmosolgo/graphiql-rails

**Comment by ThiagoCasao** [comment]
Oh man, works like a charm!

Thank you @mcelicalderon !
