### ISSUE TITLE
How to authenticate for sending multiple values to the graphql_context and mounting operations Into DummySchema

### ISSUE THREAD

**Issue by dwthien** [graphql-devise/graphql_devise#118]
I have 2 models (Admin and Customer) inheritance from User Model
   - Mounting operations Into DummySchema
   - Sending multiple values to the graphql_context and it worked for 2 models

How to authenticate field base on User Type? (Customer or Admin)

**Comment by 00dav00** [comment]
Hey @dwthien, I think what you are looking for is the `authenticable_type`.
When using a dedicated schema for gqld operation it can be done like [this](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/config/routes.rb#L15).

When using your own schema the [resources loaders in the plugin](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/app/graphql/dummy_schema.rb#L4) accept the same option:
```ruby
GraphqlDevise::ResourceLoader.new('Admin', { authenticable_type: UserType })
```

**Comment by dwthien** [comment]
Hi @00dav00 ,
I mean I have 2 resources, how to distinguish authenticate by Admin or Customer?
Example, I have some query:
field :admin_fetch, authenticate: true, authenticable_type: Admin
field :customer_fetch, authenticate: true, authenticable_type: Customer

Thank you for replying.

![image](https://user-images.githubusercontent.com/25741737/87439571-24adad80-c61b-11ea-9277-a77f2234979f.png)

**Comment by 00dav00** [comment]
I don't think I'm understanding the question. `authenticable_type` is set by resource so you can have:

```ruby
GraphqlDevise::ResourceLoader.new('Admin', { authenticable_type: AdminType }),
GraphqlDevise::ResourceLoader.new('Customer', { authenticable_type: CustomerType }),
```

or if you are using a dedicated schema:
```ruby
  mount_graphql_devise_for( 'Admin', authenticatable_type: AdminType)
  mount_graphql_devise_for( 'Customer', authenticatable_type: CustomerType)
```

Does this answer your question?
Could you post the query you are trying to perform and what are the results you expect?

**Comment by dwthien** [comment]
Hi
Sorry about my question, example: I have 2 resources (Admin and Customer) and query:
- field :admin_fetch, authenticate: true

Expect result: Only Admin account can authenticate this field.
Error: Customer still can authenticate this field.

![image](https://user-images.githubusercontent.com/25741737/87445629-79085b80-c622-11ea-9beb-8f52cb23eb60.png)
![image](https://user-images.githubusercontent.com/25741737/87445719-96d5c080-c622-11ea-91fa-708ea67c7e46.png)

**Comment by mcelicalderon** [comment]
Hey @dwthien! I see what you are saying. First of all, there is no need for you to call the `SchemaPlugin` twice, you can just pass 2 `GraphqlDevise::ResourceLoader` in the `resource_loaders` array.

And no, the gem currently doesn't support what you are trying to do (authenticate only one type of resource per field). We are thinking that might not be too difficult to support so we might actually give it a try. Just to be clear, this would work for you?

```ruby
# Fails is authenticated resource is not instance_of Admin
field :admin_fetch, authenticate: Admin

# Doesn't fail if any of the resources is authenticated
field :admin_fetch, authenticate: true

# Lambda determines if authentication is correct
field :admin_fetch, authenticate: ->(resource) { resource.instance_of?(Admin) }
```
I think we are going to go ahead and look into implementing that. But on the mean time, there is [another gem](https://github.com/exAspArk/graphql-guard) you might be interested in where you could perform these kind of checks and they can be as complex as you need them to be.

**Comment by dwthien** [comment]
Hi @mcelicalderon ,
Thank you for support from you, this is second, :))))
Seem to authenticate did not take care of the words after it, because both case below still worked.

![image](https://user-images.githubusercontent.com/25741737/87449639-a1df1f80-c627-11ea-8961-e3b847c255e6.png)
![image](https://user-images.githubusercontent.com/25741737/87449756-c9ce8300-c627-11ea-9e52-7df07cd547f6.png)

I still waiting for it, as I waited for "mounting operations Into DummySchema".

Thank you very much.

**Comment by mcelicalderon** [comment]
Oh yes, the examples I shared should not work yet. I'm just saying we might implement it in a next version ;)

**Comment by dwthien** [comment]
Haha, No Problem
Also thank you for suggesting the graphql-guard gem, It worked well.
