### ISSUE TITLE
change_headers_on_each_request question

### ISSUE THREAD

**Issue by single-stop-rj** [graphql-devise/graphql_devise#120]
### Question
```markdown
change_headers_on_each_request: This configurations defaults to false. This will allow you to store the credentials for as long as the token life_span permits. And you can send the same credentials in each request. Setting this to true means that tokens will change on each request you make, and the new values will be returned in the headers. So your client needs to handle this.
```

I see in the docs that we can change the token upon each request. Any idea of how to handle this in the client?

**Comment by mcelicalderon** [comment]
That's completely up to you on the client side. Devise token auth has this on their README about client libraries that integrate with the gem

* Seamless integration with:
  * [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth) for [AngularJS](https://github.com/angular/angular.js)
  * [Angular-Token](https://github.com/neroniaky/angular-token) for [Angular](https://github.com/angular/angular)
  * [redux-token-auth](https://github.com/kylecorbelli/redux-token-auth) for [React with Redux](https://github.com/reactjs/react-redux)
  * [jToker](https://github.com/lynndylanhurley/j-toker) for [jQuery](https://jquery.com/)

**Comment by mcelicalderon** [comment]
Closing this one as the client implementation is not in the scope of this gem. If you are using Apollo as your client @single-stop-rj , I would suggest looking into the different link implementations they provide. You can probably implement logic there in each response that will take care of storing the new headers in each response you receive. Take a look at this page https://www.apollographql.com/docs/link/links/http/#afterware-data-manipulation

**Comment by SimonBrazell** [comment]
For anyone that stumbles across this question, this is how I achieved it using Angular and Apollo Angular for the front-end:

```
// src/app/graphql.module.ts

import { NgModule } from "@angular/core";
import { Apollo } from "apollo-angular";
import { InMemoryCache, ApolloLink } from "@apollo/client/core";
import { HttpLink } from "apollo-angular/http";
import { environment } from "src/environments/environment";
import { setContext } from "@apollo/client/link/context";
import { HttpClientModule } from "@angular/common/http";
import { TokenService } from "./services/token.service";
import { Router } from "@angular/router";

@NgModule({
  exports: [HttpClientModule],
})
export class GraphQLModule {
  constructor(
    private apollo: Apollo,
    private httpLink: HttpLink,
    private tokenService: TokenService,
    private router: Router
  ) {
    this.init();
  }

  private async init(): Promise<void> {
    const auth = setContext(async () => {
      const credentials = await this.tokenService.getCredentials();
      if (credentials) {
        return {
          headers: {
            "access-token": credentials.accessToken,
            client: credentials.client,
            expiry: credentials.expiry,
            "token-type": credentials.tokenType,
            uid: credentials.uid,
          },
        };
      } else {
        return {};
      }
    });

    const middleware = new ApolloLink((operation, forward) =>
      forward(operation).map((result) => {
        if (!result.errors) {
          const context = operation.getContext();
          if (context.response.headers.has("access-token")) {
            this.tokenService.setCredentials({
              accessToken: context.response.headers.get("access-token"),
              client: context.response.headers.get("client"),
              expiry: context.response.headers.get("expiry"),
              tokenType: context.response.headers.get("token-type"),
              uid: context.response.headers.get("uid"),
            });
          }
        }

        return result;
      })
    );

    const link = ApolloLink.from([
      auth,
      middleware,
      this.httpLink.create({ uri: environment.api }),
    ]);
    const cache = new InMemoryCache();
    this.apollo.create({
      link,
      cache,
    });
  }
}

```
The `auth` link retrieves the credentials from my token service while the `middleware` link gets the response headers which contain the new/refreshed credentials and stores them in the same service for use in the next request.
