### ISSUE TITLE
undefined method `resource_class' for nil:NilClass while trying to run mutations on /graphiql

### ISSUE THREAD

**Issue by nenjamin2405** [graphql-devise/graphql_devise#131]
### Describe the bug

Hi guys, thanks for this great gem which supports using devise token auth in graphql ruby and I'm very excited to use it. As described above, I met that error (image attached below) while trying to run mutations generated by graphql_devise gem (useSignUp, userLogin, ...). 

![image](https://user-images.githubusercontent.com/16648769/91662529-4bfa0480-eb0d-11ea-8710-19490d8e5297.png)

I used the option `Mounting Operations in Your Own Schema`, I already run the command `bundle exec rails g graphql_devise:install User --mount MyOwnSchemaName`, below are all of files changes and my configurations, please let me know if I miss anything:

1. In my own graphql schema, it inserted the snippet

```
 use GraphqlDevise::SchemaPlugin.new(
    query:            Types::QueryType,
    mutation:         Types::MutationType,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new('User'),
    ],
    authenticate_default: false # <-- I added this
  )
```

2. In routes.rb, I added the below line to use current_user in graphql_controller:

```
 devise_for :users, ActiveAdmin::Devise.config

```

3. In grapql_controller.rb:

- Added: `  include GraphqlDevise::Concerns::SetUserByToken`
- My def execute:
```
  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      current_user: current_user,
    }
    result = MyOwnSchemaName.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end
```

4. In User model, I don't need the confirmable so I removed it
```
class User < ApplicationRecord
  devise :database_authenticatable,
  :registerable,
  :recoverable,
  :rememberable,
  :trackable,
  :lockable,
  :validatable

  include GraphqlDevise::Concerns::Model
end
```

### Environment

My Gemfile and Gemfile.lock
https://gist.github.com/nenjamin2405/888a79ef35f1b826df7140af42972eb4

### Steps to reproduce

(Write your steps here:)

1. Run Rails Server
2. Go to localhost:3000/graphiql
3. Try to run a mutation to test
4. Issue appears like the image below

![image](https://user-images.githubusercontent.com/16648769/91662523-43093300-eb0d-11ea-995f-bb7d623c924f.png)

### Expected behavior

Expect new user is created in database and the mutation returns credentials in payload

### Actual behavior

Error in the image attached above happens

### Reproducible demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by mcelicalderon** [comment]
Hey @nenjamin2405! Looks like you are missing the right context on your controller. Please take a looks at [this configuration step](https://github.com/graphql-devise/graphql_devise#authenticate-in-your-gql-schema). I hope that does it.

**Comment by nenjamin2405** [comment]
Hi @mcelicalderon, thanks a lot for your super fast response and clarification, it works now!!!

**Comment by antarr** [comment]
@nenjamin2405 @mcelicalderon What is the actual solution. It's not clear to me. I'm having the same issue when trying to log in or signup. When I pry in `params[:operationName]` is nil

**Comment by mcelicalderon** [comment]
Hey @antarr! If you are having exactly the same problem as @nenjamin2405 look at the link I posted. But it all came down to doing this

`result = DummySchema.execute(params[:query], context: graphql_context(:user))`

You need to send the right context to the execute method on the schema.
