### ISSUE TITLE
Replacing Devise Gem with GraphQLDevise

### ISSUE THREAD

**Issue by rcaf-anthony** [graphql-devise/graphql_devise#132]
### Question

First, I'm new to Ruby on Rails, coming from a .Net background, so please excuse the total newbie question.

I have an application that currently uses the Devise Gem, and has a GraphQL endpoint.  How can I replace the current Devise Gem with GraphQLDevise, so that the endpoint is secured as well?  

I tried following the instructions in the README.md
1. I've added this Gem to the Gemfile, 
2. run the install, 
3. and added the SchemaPlugin to my Schema, 

Now, the application no longer redirects to any of the devise routes for user login, or sends emails for user functions.  
1. Will I need to create user mutations and re-write the routes, if so, can you provide, or point me to a quick demo of how?  
2. Will I need to remove the Devise Gem from the Gemfile?
3. What about the Devise routes, should I remove the devise views as well?

**Comment by 00dav00** [comment]
Hi @rcaf-anthony , I would suggest you checking the [dummy rails project](https://github.com/graphql-devise/graphql_devise/tree/master/spec/dummy) used for the gem testing. In there you can find the basic structure to use the gem.

You can get the most the gem if you are creating an API with graphql on top of it. If you are using a full stack rails project, meaning that you do render rails views, you probably should keep using standard devise, otherwise you will need to redo all the screens that devise already give you for free and call the mutations/queries from there.

**Comment by rcaf-anthony** [comment]
Hi @00dav00, 

The biggest problem is that the application is currently built and functioning with Rails/React/Devise/GraphQL where:
 - Rails :  controls the data, 
 - GraphQL : handles queries and mutations to provide a single endpoint
 - Devise : handles all user functions (login, logout, confirmation, etc.), including UI
 - React : provides UI for everything except user functions

and I'm trying to use the graphql-devise gem to implement security in the already built graphql endpoint.  

>  you probably should keep using standard devise,
Are you suggesting that I could use the standard devise and just add a `before_action :authenticate_user!` in my `graphql_controller.rb`  or do I have to use the token authentication?  At this point I see no need to know which user is performing a request as the application isn't that complex, so I don't think that the token authentication is required, but seeing as how I'm a total newbie with Ruby on Rails, I'm not sure exactly how to proceed.

**Comment by 00dav00** [comment]
I see @rcaf-anthony , now this looks like valid use case for the use gql-devise.
So what I think you should do is:

- Create the views that think your app for auth purposes in react
- Call the mutations/queries your app needs, here is a [list of the operations available](https://github.com/graphql-devise/graphql_devise#important-2) in the gem, checking the dummy project can help here too

What operations you should use depends on your project requirements.

> Are you suggesting that I could use the standard devise and just add a before_action :authenticate_user! 
Not really, that entirely depends on the business rules for your project

Hope this helps!

**Comment by rcaf-anthony** [comment]
Thanks for the advice, I'll keep working on the integration of this gem then.

**Comment by rcaf-anthony** [comment]
Hey @00dav00 ,
Just FYI. 
I tried like above, just putting `before_action :authenticate_user!` in the `graphql_controller.rb` and it works in our setup.  
I can run queries and mutations from the React Frontend, and query from the graphiql UI but I can not get even the schema to show in the graphiql UI it just shows 'unsupported token < in JSON' or something like that in the response, and shows that the devise gem is trying to redirect to the sign in page in the Network tab of the DevTools.
If we do something more complex, I might ask for more help, but for the time being I won't be implementing this gem in that project. (maybe next project, just so I can get a chance to use it!)
