### ISSUE TITLE
Requiring graphql-ruby to respond to GET requests can lead to security issue

### ISSUE THREAD

**Issue by galiminus** [graphql-devise/graphql_devise#137]
### Describe the bug

It seems that some queries in graphql_devise requires graphql-ruby to respond to GET requests:

```
# From the dummy app
  get '/api/v1/graphql', to: 'api/v1/graphql#graphql'
  post '/api/v1/graphql', to: 'api/v1/graphql#graphql'
```

As far as I can tell and after browsing through the doc, it seems that graphql-ruby was never intended to serve GET requests (at least I couldn't find anything about it in the doc). This can lead to some security issues since graphql-ruby will execute any mutations on GET, and without the user knowing it (for example, by using the `src` attribute of an `img` tag).

As a an example, while Apollo Server allows GET requests it also prevents any mutations from being executed (see https://www.apollographql.com/docs/apollo-server/v1/requests/).

### Expected behavior

I'm really not sure how to fix this, I'm looking into ways of updating `graphql_controller.rb` to prevent it from passing mutations down to  `XXXSchema.execute` when the request uses the GET method.

Thanks for your help!

**Comment by mcelicalderon** [comment]
The Apollo link you shared is precisely why we enabled the GET method. From a quick search I can't find anywhere in the docs or specification something that states that mutations cannot be executed via GET request, [this](https://graphql.org/learn/serving-over-http/#http-methods-headers-and-body) would be a nice place to put it. Nothing on the graphql ruby gem. I understand what you are saying, with REST by convention you would not have endpoints that change the state of the server in any way over GET requests, but graphql in general does a lot of things differently and generally disregards the layer where the query is transmitted.
Anyway, let me know if you find something related to this and we'll be happy to look deeper into ii, I will also do some more research as soon as I get some time

**Comment by mcelicalderon** [comment]
Closing this one as no more information was provided on it, but feel free to reopen if any you find anything else on this subject.
