### ISSUE TITLE
Testing Authenticated Elements

### ISSUE THREAD

**Issue by armstnp** [graphql-devise/graphql_devise#138]
### Question

I'm currently trying to set this up, but I'm having difficulty running any form of integration test on the schema itself.

I have a number of tests in a format similar to [that specified by the GraphQL-Ruby documentation](https://graphql-ruby.org/testing/integration_tests.html#testing-interface-level-behaviors), but with this gem in operation, all my tests now fail with the claim that the user is not signed in.

I'm executing queries from the schema, not the controller, but the schema and controller are now more tightly coupled since the schema now delegates to the controller for authentication. Is there a recommended means by which a user can be readily specified for a schema call? I've been digging through the gem callchain and I can't seem to figure out how this might be done. I've tried creating a context for the `Schema#execute` call with a stubbed controller, but that doesn't seem to do the trick.

**Comment by armstnp** [comment]
Update: I took a break, came back with fresh eyes, and found a way to make it work. I'll try and extract the modifications that made it work, in case it's of use for either adding to the library, or as reference for other implementers. The controller-schema coupling is still somewhat concerning, but the interface is narrow enough to be simply stubbed.

**Comment by mcelicalderon** [comment]
Hey @armstnp! Thanks for looking into this. Yes that coupling is something we should look into. That came as a result of a problem with autoload and how devise setups a model, that's why we delegate to the controller when the request is made, to make sure the schema and model configuration is ready. But we need to find a better way to fix this.

**Comment by alexanderdavide** [comment]
@armstnp Currently implementing similar tests. I am authenticating in the GraphQL schema. Can you please explain how you did this?

**Comment by mcelicalderon** [comment]
Hey @alexanderdavide! Until we improve the architecture of this part of the code I don't think there's a better way to test only the schema without stubbing some objects. Something like this should do given you are using the `User` model and RSpec, but you should be able to stub the same things given you are using a different test framework

```ruby
 # this user object can be any that you want to be available during the query in context[:current_resource]
authenticated_user = User.first

controller_double = double(:controller, set_resource_by_token: authenticated_user)
DummySchema.execute(query, context: { resource_name: :user, controller: controller_double })
```

I think this should be enough to test your own queries and mutations. The mutations and queries provided by this gem do use a wider interface of the controller, so you might need to stub some other things if you test those

**Comment by keithmgould** [comment]
The above worked for me but I only found this after two hours of searching. (I should have looked here first perhaps). I think its fair to assume a lot of people want this information. It worked for me, and I hope it makes it into the documentation somewhere.

**Comment by mcelicalderon** [comment]
Hey @keithmgould! You are absolutely right. We actually want to improve this part so we don't have to inject the controller into the context. I hope we can fix it soon.

**Comment by 00dav00** [comment]
@armstnp With the changes on #149 change the gem:
- Will only try to set current resource for authenticated fields
- Won't try to set the `current_resource` using the auth token if it is already present, this allows setting it directly on scheam tests like in this [shared context](https://github.com/graphql-devise/graphql_devise/blob/master/spec/support/contexts/schema_test.rb)
