### ISSUE TITLE
Potential Bug For MailHelper

### ISSUE THREAD

**Issue by dmc2015** [graphql-devise/graphql_devise#144]
Hello

I am not sure if it is a bug or if I did something wrong.

I was getting this error:

```
{
  "errors": [
    {
      "message": "undefined method `confirmation_query' for #<#<Class:0x00007fcd3cf1b5b0>:0x00007fcd3cf19c88>\nDid you mean?  confirmation_url\n               confirmation_path",
```

I eventually was able to find where `confirmation_query` is located.

I resolved it by adding:

`include GraphqlDevise::MailerHelper`

to my Graphql Schema

I am wondering if this is the correct way to do this or if there is a better way. I don't see `MailerHelper` in the documentation so I figured maybe it is supposed to be included in some other way. Considering this is security I prefer it to be as standard as possible.

### Steps to reproduce

(Write your steps here:)

1. Add and go through normal setup
2. Use the default route
3. Use the Authenticate In Graphql
4. Send an authentication request via graphiql

```
mutation signUp {
   userSignUp (
    email: "user@gmail.com"
    password: "xxx"
    passwordConfirmation: "xxx"
  ) {
    authenticatable { email }
    }
}
```
  

### Expected behavior
I expect it to authenticate the user

(Write what you thought would happen.)

### Actual behavior

Returns an error:

```
  "errors": [
    {
      "message": "undefined method `confirmation_query' for #<#<Class:0x00007fcd3cf1b5b0>:0x00007fcd3cf19c88>\nDid you mean?  confirmation_url\n               confirmation_path",
```

Sample Files:

Graphql Schema

```
# frozen_string_literal: true
class Schema < GraphQL::Schema
  # include GraphqlDevise::MailerHelper

  # It's important that this line goes before setting the query and mutation type on your
  # schema in graphql versions < 1.10.0
  use GraphqlDevise::SchemaPlugin.new(
    query:            Types::QueryType,
    mutation:         Types::MutationType,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new('User', only: %i[login confirm_account sign_up])
      # GraphqlDevise::ResourceLoader.new('User', only: %i[login confirm_account logout sign_up update_password send_password_reset check_password_token] )

    ]
  )

  mutation(Types::MutationType)
  query(Types::QueryType)

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  use GraphQL::Pagination::Connections
end
```

User Model:

```
# frozen_string_literal: true

class User < ActiveRecord::Base

  before_validation do
    self.uid = email if uid.blank?
  end

  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable, :omniauthable
  include GraphqlDevise::Concerns::Model

  include DeviseTokenAuth::Concerns::User


end
```

Devise Token Auth.rb

```
# frozen_string_literal: true

DeviseTokenAuth.setup do |config|
  config.change_headers_on_each_request = false
  config.default_confirm_success_url = 'confirmed'
end
```

**Comment by 00dav00** [comment]
Hi @dmc2015 , the mailer helper is loaded with the [gem routes](https://github.com/graphql-devise/graphql_devise/blob/master/config/routes.rb#L18).
Is this loaded with the configuration you are using?

Also (but probably no related), you are including DTA and gql-devise concerns in the user model, since they have similar methods this can cause you problems in the future.
```
  include GraphqlDevise::Concerns::Model

  include DeviseTokenAuth::Concerns::User # <----------- remove
```

**Comment by dmc2015** [comment]
It's not being loaded automatically for me based on what I have in my routes.

I have to have an include of it in my schema, having it in my routes works also.

If it isn't included I am getting:

```
{
  "errors": [
    {
      "message": "undefined method `confirmation_query' for #<#<Class:0x00007fcd3cf1b5b0>:0x00007fcd3cf19c88>\nDid you mean?  confirmation_url\n               confirmation_path",
```

Routes:

```
# frozen_string_literal: true
include GraphqlDevise::MailerHelper

Rails.application.routes.draw do
  root to: 'graphql_devise/graphql#auth'

  mount_graphql_devise_for 'User', at: 'graphql_auth'

  get 'none/graphql_route/:id', to: 'none#graphql_route'

  if Rails.env == 'development'
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: 'graphql#execute'
  end

  post '/graphql', to: 'graphql#execute'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
```

**Comment by dmc2015** [comment]
I'll try to re-create in a sample app

**Comment by mcelicalderon** [comment]
That is perfect @dmc2015, thank you! I think it is weird that you have to include the helper in the routes,but we'll definitively get a better idea if you push a sample app we can look into. Try using the same versions of the gems as the ones you use where you see the error

**Comment by wolak88** [comment]
I'm encountering the same error, adding MailerHelper to routes works for me as well though
