### ISSUE TITLE
Adding a field to SignUp when mounting auth in the main schema

### ISSUE THREAD

**Issue by keithmgould** [graphql-devise/graphql_devise#145]
### Related

This issue is similar to [this issue](https://github.com/graphql-devise/graphql_devise/issues/28) however in the linked issue, a different route for auth was used to solve.

### Question

The question is: when using a *single* endpoint, where auth is merged into the main graph, how do we add another field to SignUp (lets call the new field `name`).

### Status

I currently have the app working with auth merged into the main schema, as explained in the readme.

### Code

```
# schema
class MySchema < GraphQL::Schema

  use GraphqlDevise::SchemaPlugin.new(
    query:            Types::QueryType,
    mutation:         Types::MutationType,
    authenticate_default: false,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new('User', {})
    ]
  )


  mutation(Types::MutationType)
  query(Types::QueryType)

  # Opt in to the new runtime (default in future graphql-ruby versions)
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  # Add built-in connections for pagination
  use GraphQL::Pagination::Connections
end
```

```
# controller that loads schema
class GraphqlController < ApplicationController
  include GraphqlDevise::Concerns::SetUserByToken
  
  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    result = MySchema.execute(query, variables: variables, context: graphql_context(:user), operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

 # ... more code here but is boilerplate
```

```
# routes.rb, standard

Rails.application.routes.draw do  
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  get "/graphql", to: "graphql#execute"

  root 'home#index'
  get '*path', to: 'home#index'
end
```

I'd like to add a field to Signup, so I made a mutation (as seen in the spec/dummy app):
```
module Mutations
  module Users
    class SignUp < GraphqlDevise::Mutations::SignUp
      argument :name, String, required: true
      field :user, Types::UserType, null: true

      def resolve(email:, **attrs)
        original_payload = super
        original_payload.merge(user: original_payload[:authenticatable])
      end
    end
  end
end
```

### Summary 

Given above, I'd like the gem to *use* this mutation, however I do not want to create a new auth route. I want to keep the single endpoint.  

I don't know how to ask the gem to use this mutation. The mutation is ignored. ( I am not getting any explicit errors/500s/etc...)

Thank you!

**Comment by keithmgould** [comment]
Of course I figured it out right after posting the question. 

```
      GraphqlDevise::ResourceLoader.new('User', {
        operations: {
          sign_up: Mutations::Users::SignUp
        }
      })
```

Hope this helps someone!

**Comment by 00dav00** [comment]
It happens from time to time, thanks @keithmgould !

BTW, is there something in the readme that can make this config more obvious? We are happy to receive suggestions on that.

**Comment by keithmgould** [comment]
As i re-read the README it feels like you made it pretty clear:

> operations: Specifying this is optional. Here you can override default behavior by specifying your own mutations and queries for every GraphQL operation.

Possible though that since at least two people were a bit stuck on it (despite a clear readme) it might be worth adding a small section on this exact topic: "Adding fields to SignUp: Two ways" which could cover the way I did it, and also the extra route method. In a sense this part of the readme would be redundant, but might still help users searching for this specific thing. Hard for me to know how many people get tripped up on this though, might be too edge-casey.

**Comment by 00dav00** [comment]
Hi @keithmgould , just saw this. I'm not completely sure about where that change should go, would you be interested in creating a PR for this change?

**Comment by keithmgould** [comment]
Hey @00dav00 will do. Will try and get to it this weekend.

**Comment by 00dav00** [comment]
Thanks @keithmgould !!

**Comment by guillaume-gomez** [comment]
many thanks @keithmgould . Your example should be in readme :100:
