### ISSUE TITLE
I can't user current_resource

### ISSUE THREAD

**Issue by fkoyo** [graphql-devise/graphql_devise#153]
when I tried to user context[:current_resource], I can't use  ```context[:current_resource]```
why? 

thanks

### configration

install into my schema

```
class MySchema < GraphQL::Schema
  use GraphqlDevise::SchemaPlugin.new(
    query:            Types::QueryType,
    mutation:         Types::MutationType,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new('User'),
    ],
    authenticate_default: false
  )
  mutation(Types::MutationType)
  query(Types::QueryType)

  # Setup GraphQL to use the built-in lazy_resolve method
  use BatchLoader::GraphQL
end
```

route.rb:
```
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # For graphql
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute" 
  get "/graphql", to: "graphql#execute" 
```
graqhql_controller.rb:
```
def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    result = BusinessCloudSchema.execute(query, variables: variables, context: graphql_context(:user), operation_name: operation_name)
    render json: result unless performed?
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end
```

user_update_input.rb
```
module Types
  class UserUpdateInput < Types::BaseInputObject
    argument :fist_name, String, required: true
    argument :last_name, String, required: true
    argument :position, String, required: false
    argument :image, ApolloUploadServer::Upload, required: false

    def update!
     user = context[:current_resource]
      user.assign_attributes(first_name: first_name, last_name: last_name, image: valid_image)
      user.update
      {
        errors: user_errors(user.errors),
        user: user.reload
      }
    end

    private

    def valid_image
      image if image&.is_a?(ApolloUploadServer::Wrappers::UploadedFile)
    end
  end
end
```

update_user.rb
```
module Mutations
  class UpdateUser < BaseMutation
    field :user, Types::UserType, null: true

    argument :user, Types::UserUpdateInput, required: true

    def resolve(user:)
      {
        user: user.update!
      }
    end
  end
end
```

iI execute the following mutation in graphiql
```
mutation{
  updateUser(input: { clientMutationId: "", user: {fistName: "aa", lastName: "bb", position: "manager"}}) {
    clientMutationId
    user{
      email
      firstName
      image
      lastName
      position
    }
  }
}
```

**Comment by 00dav00** [comment]
Hi @fkoyo , I think you are missing the concern that set the user, did you use the generator to install the schema? 
Please check this part of [the readme](https://github.com/graphql-devise/graphql_devise#authenticating-controller-actions) for reference

**Comment by fkoyo** [comment]
@00dav00 
thanks!! I install the gem using ```$ bundle exec rails g graphql_devise:install User``` command, 
but I added ```authenticate_default: false```  to  my_schema.rb like the following:

```
class BusinessCloudSchema < GraphQL::Schema
  use GraphqlDevise::SchemaPlugin.new(
    query:            Types::QueryType,
    mutation:         Types::MutationType,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new('User'),
    ],
    authenticate_default: false
  )
  mutation(Types::MutationType)
  query(Types::QueryType)

  # Setup GraphQL to use the built-in lazy_resolve method
  use BatchLoader::GraphQL
end
```

I deleted it.

so, another error occur like the image]
```
  "data": null,
  "errors": [
    {
      "message": "__schema field requires authentication",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "__schema"
      ],
      "extensions": {
        "code": "AUTHENTICATION_ERROR"
      }
    }
  ]
}
```
![スクリーンショット 2021-02-25 22 45 53](https://user-images.githubusercontent.com/18605223/109162408-8510ea00-77bb-11eb-9202-3edfdcda8a35.png)


I'm in very trouble. please give me an advise..

thanks!

**Comment by 00dav00** [comment]
@fkoyo that is a problem we just noticed, if you want the introspection query to work with the schema plugin you will need to set the `authenticate_default: false` option in you schema or make sure the auth token is set in the browser/client you are using.


About the `current_user` were you able to check the documentation about the `SetUserByToken` concern? Is `current_user` available now?
Also, could you post the controller were the schema is mounted?

**Comment by fkoyo** [comment]
@00dav00 
thanks!!

>  if you want the introspection query to work with the schema plugin you will need to set the authenticate_default: false option in you schema or make sure the auth token is set in the browser/client you are using.

I understand!


I post my graphql_controller.rb
```
lass GraphqlController < ApplicationController
  include ActionController::HttpAuthentication::Token::ControllerMethods
  include GraphqlDevise::Concerns::SetUserByToken

  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  protect_from_forgery with: :null_session

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    result = BusinessCloudSchema.execute(query, variables: variables, context: graphql_context(:user), operation_name: operation_name)
    render json: result unless performed?
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: {errors: [{message: e.message, backtrace: e.backtrace}], data: {}}, status: 500
  end
end
```

and  i want to try update_user so I create ```update_user_input.rb``` and  ```update_user.rb``` file.

```
module Types
  class UserUpdateInput < Types::BaseInputObject
    argument :first_name, String, required: true
    argument :last_name, String, required: true
    argument :position, String, required: false
    argument :image, ApolloUploadServer::Upload, required: false
  end
end
```

```
module Mutations
  class UpdateUser < BaseMutation
    field :user, Types::UserType, null: true
    argument :user, Types::UserUpdateInput, required: true

    def resolve(user:)
      binding.pry
      current_user = context[:current_resource]
      current_user.update!(first_name: user.first_name, last_name: user.last_name,  position: user.position, image: user.image, sutats: 90 )
      {
        user: current_user
      }
    end
  end
end
```

so, in pry
- current_user = nil
- context[:current_user] = nil
- context[:current_resource] = nil

in addition 
route.rb 

```
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # For graphql
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  get   "/graphql", to: "graphql#execute"
end
``

![スクリーンショット 2021-02-26 0 10 35](https://user-images.githubusercontent.com/18605223/109173363-189be800-77c7-11eb-97d1-c8b4c3772896.png)


please help...

thanks!!

**Comment by 00dav00** [comment]
@fkoyo since the schema is set not to consider fields `not authenticated`  by default, you will need to set your field as authenticated with adding it to the schema

```
field :update_user, Mutations::UpdateUser, null: false, authenticate: true
```

Not authenticated fields are considered public, hence no current_user is set.
Could you try this please?

**Comment by fkoyo** [comment]
@00dav00 
thanks!!

I added ```authenticate: true```  into mutation_type.rb like the following:
```
module Types
  class MutationType < Types::BaseObject
    field :register_organization,   mutation: Mutations::RegisterOrganization
    field :update_user,             mutation: Mutations::UpdateUser, authenticate: true
  end
end
```

but, error that ```updateUser field requires authentication``` occur 

I think ```authenticate: false```  is right.
I tried but, nothing changed.


```undefined method `update!' for nil:NilClass" ```

oh,,,,

**Comment by fkoyo** [comment]
I added ```, authenticate: true``` like the following:
```
module Types
  class MutationType < Types::BaseObject
    field :register_organization,   mutation: Mutations::RegisterOrganization
    field :update_user,             mutation: Mutations::UpdateUser, null: false, authenticate: true
  end
end
```
```updateUser field requires authentication```

so, I have already log in. I tried login one more.

![Snip20210226_12](https://user-images.githubusercontent.com/18605223/109231221-7f41f580-7809-11eb-8826-bff28068b5e9.png)

but ```updateUser field requires authentication``` .
what do I  have to  do after login?

please..

thanks!

**Comment by fkoyo** [comment]
@00dav00 
I added ```, authenticate: true``` like the following:
```
module Types
  class MutationType < Types::BaseObject
    field :register_organization,   mutation: Mutations::RegisterOrganization
    field :update_user,             mutation: Mutations::UpdateUser, null: false, authenticate: true
  end
end
```
```updateUser field requires authentication```

so, I have already log in. I tried login one more.

![Snip20210226_12](https://user-images.githubusercontent.com/18605223/109231221-7f41f580-7809-11eb-8826-bff28068b5e9.png)

but ```updateUser field requires authentication``` .
what do I  have to  do after login?

please..

thanks!

**Comment by fkoyo** [comment]
I got it!
I register headers  accestoken ui client and I try it I can update_user!

thanks a lot!!

**Comment by 00dav00** [comment]
Awesome! glad to read this @fkoyo. I'm closing this issue since we have a another where we keep track of the problem with the introspection query.

**Comment by NathanielAwoke** [comment]
> @fkoyo since the schema is set to consider fields `not authenticated` by default, you will need to set your field as `authenticated` when adding it to the schema
> 
> ```ruby
> field :update_user, Mutations::UpdateUser, null: false, authenticate: true
> ```
> 
> Not authenticated fields are considered public, hence no current_user is set. Could you try this please?

Is there any way to set current_resource for public fields ?
