### ISSUE TITLE
can we user devise_invitable?

### ISSUE THREAD

**Issue by fkoyo** [graphql-devise/graphql_devise#156]
can we user [devise_invitable](https://github.com/scambra/devise_invitable)？

**Comment by mcelicalderon** [comment]
Hey @fkoyo. Yes you can, but this gem doesn't add invitable behavior to your models. So, you can add the invitable gem and use some of it's methods to implement your own invitation flow. I would advise you read through devise_invitable's docs and really understand how it works. I have done it before and your mutation could contain something like this:

```ruby
def invite_user(user)
  user.skip_invitation = true
  user.invitation_sent_at = Time.now
  user.invite!(current_user)

  InvitationsMailer.invite_user_to_account(user, user.raw_invitation_token).deliver_later
end
```
Or don't `skip_invitation` and calling `invite!` will trigger the gem's mailer, so you can go either way. [Usage section](https://github.com/scambra/devise_invitable#usage-) on Devise Invitable's readme is pretty clear on different ways to accomplish this.

**Comment by fkoyo** [comment]
@mcelicalderon 
so thanks!! I got it!

excuse me! one More question.

I want to accept the invitation by clicking the link in the email sent by devise_invitable.

but the following error occurred when I invite another user by exceute the following mutation
```undefined method `accept_invitation_url' for #<ActionView::Base:0x000000000135d8>"```

```
mutation {
  inviteUser(input: {emails: "taro.tanaka@sample.co.jp"}) {
    clientMutationId
  }
}
```

do I have to set  API endpoint  ``` accept_invitation_url```?
Can I accept the invitation by clicking the link in the email?

FYI: https://github.com/zauberware/rails-devise-graphql/blob/master/app/graphql/mutations/users/accept_invite.rb

mutations/invit_user.rb 
```
module Mutations
  class InviteUser < BaseMutation
    description 'Invites an user to your account.'

    argument :emails,                String,  required: true
    argument :authority,             Integer, required: true

    def resolve(emails:, authority:)
      # create a dummy user object to check ability against create
      return false if emails.blank? && authority.blank?
      success_counts = 0
      invite_emails = emails.strip.split(/\R|\,/) if emails.present?
      users = []
      binding.pry
      invite_emails.each do |invite_email|
        resource = User.invite!({ email: "#{invite_email}", organization_id: context[:current_resource].organization_id, authority: authority}, context[:current_resource])
        resource_invited = resource.errors.empty?
        yield resource if block_given?
        success_counts += 1 if resource_invited
        users << resource
      end
      {
        users: users
      }
    end
  end
end
```

devise/mailer/invitation_instructions.html
```
<p><%= t("devise.mailer.invitation_instructions.hello", email: @resource.email) %></p>

<p><%= t("devise.mailer.invitation_instructions.someone_invited_you", url: "http://localhost:3000/") %></p>

<p><%= link_to t("devise.mailer.invitation_instructions.accept"), accept_invitation_url(@resource, invitation_token: @token) %></p>

<% if @resource.invitation_due_at %>
  <p><%= t("devise.mailer.invitation_instructions.accept_until", due_date: l(@resource.invitation_due_at, format: :'devise.mailer.invitation_instructions.accept_until_format')) %></p>
<% end %>

<p><%= t("devise.mailer.invitation_instructions.ignore") %></p>
```


please help me.
thanks!

**Comment by SimonBrazell** [comment]
@fkoyo getting the same error - `undefined method `accept_invitation_url'`, how did you solve this?
