### ISSUE TITLE
How to use with omniauth oauth?

### ISSUE THREAD

**Issue by nopain2110** [graphql-devise/graphql_devise#167]
### Question

I want to implement oauth with omniauth without mount devise_token_auth to my rest routes.
Is it possible?
Thank you!

**Comment by mcelicalderon** [comment]
Hey @nopain2110! We don't support oauth authentication. For that I think you will defintively need at least a REST endpoint for the callback. [DTA](https://github.com/lynndylanhurley/devise_token_auth) definitively supports oauth.

**Comment by nopain2110** [comment]
Thanks for your quick response.
I think I have to use DTO for oauth.
