### ISSUE TITLE
Sign in user after sign_up?

### ISSUE THREAD

**Issue by yshmarov** [graphql-devise/graphql_devise#182]
Hi there! Thanks for the great gem! 
Small question:
It seems to me that the user does not get authenticated/signed_in after sign_up. Right?
https://github.com/graphql-devise/graphql_devise/blob/master/lib/graphql_devise/mutations/sign_up.rb#L40
How can I get the user logged in after sign_up?

**Comment by mcelicalderon** [comment]
Hey @yshmarov! So if you are not using the `:confirmable` module on your model, you should actually receive credentials after sign up. The gem's behavior is to prevent login until you confirm your account. If you are not using the confirmable module, do let me know so I can look into that.

Even with the module enabled, you can override `active_for_authentication?` in your model. Returning `true` will sign in the user on sign up. Now, I have to check if we do some kind of check for this method in every request, but I can't recall right now. Anyway, overriding that method should also fix that, but kind of defeats the purpose of the confirmable module.

**Comment by mcelicalderon** [comment]
Closing this one as no further feedback was received. signUp mutation is already removed on master, but the new register mutation behaves the same way. Feel free to reopen if you think there's still something wrong with the current behavior
