### ISSUE TITLE
cannot use newer version of rubocop ( 1.18, 1.19, 1.20 ) with the graphql-devise gem 

### ISSUE THREAD

**Issue by Qchmqs** [graphql-devise/graphql_devise#195]
https://github.com/graphql-devise/graphql_devise/blob/e9c9a8f6cf8ad9851261e907347e7a3c8d635e3e/.rubocop.yml#L94

Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.

**Comment by 00dav00** [comment]
Hi @Qchmqs , we are keeping version of rubocop configuration to be compatible with older versions of ruby. We are planning to update it after removing support for them in V1 release.  What we do is keep a different rubocop config file uncommited in our locals. Perhaps that can work you as well in the mean time.

**Comment by Qchmqs** [comment]
hi @00dav00 , it's causing me problems when I tried to setup a linting job in CircleCi, do you know of a way to tell rubocop to ignore gem introduced lints ?

**Comment by mcelicalderon** [comment]
@Qchmqs I don't think the default behavior is to inherit config from gems. You can do that with https://docs.rubocop.org/rubocop/configuration.html#inheriting-configuration-from-a-dependency-gem but you should get that by default. I would advise checking your config file again. Maybe an inherited config is doing gem files inheritance
