### ISSUE TITLE
Deprecation warnings on sidekiq process

### ISSUE THREAD

**Issue by wolak88** [graphql-devise/graphql_devise#204]
### Describe the bug

I get deprecations warning when starting sidekiq process.

### Expected behavior

No deprecation warnings

### Actual behavior

This is how I mount my schema:
```
use GraphqlDevise::SchemaPlugin.new(
    query: Types::QueryType,
    mutation: Types::MutationType,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new(User,
                                        operations: {
                                          login: Mutations::Login,
                                          sign_up: Mutations::SignUp,
                                          confirm_account: Queries::UserConfirmAccount,
                                        }),
    ],
  )
```

E.g. custom login mutation:
```
module Mutations
  class Login < GraphqlDevise::Mutations::Login
    field :authenticatable, Types::UserType, null: true

    def resolve(email:, password:)
      super do |user|
          custom_logic_here
        end
      end
    end
  end
end

```

Logs from sidekiq process:
```
2021-12-27T09:39:17.517Z pid=16097 tid=i71 WARN: DEPRECATION WARNING: `sign_up` is deprecated and will be removed in a future version of this gem.
use register instead

You can supress this message by skipping `sign_up` on your ResourceLoader or the
mount_graphql_devise_for method on your routes file.
 (called from new at /application/app/graphql/application_schema.rb:18)
2021-12-27T09:39:17.518Z pid=16097 tid=i71 WARN: DEPRECATION WARNING: `update_password` is deprecated and will be removed in a future version of this gem.
use update_password_with_token instead

You can supress this message by skipping `update_password` on your ResourceLoader or the
mount_graphql_devise_for method on your routes file.
 (called from new at /application/app/graphql/application_schema.rb:18)
2021-12-27T09:39:17.518Z pid=16097 tid=i71 WARN: DEPRECATION WARNING: `send_password_reset` is deprecated and will be removed in a future version of this gem.
use send_password_reset_with_token instead

You can supress this message by skipping `send_password_reset` on your ResourceLoader or the
mount_graphql_devise_for method on your routes file.
 (called from new at /application/app/graphql/application_schema.rb:18)
2021-12-27T09:39:17.518Z pid=16097 tid=i71 WARN: DEPRECATION WARNING: `resend_confirmation` is deprecated and will be removed in a future version of this gem.
use resend_confirmation_with_token instead

You can supress this message by skipping `resend_confirmation` on your ResourceLoader or the
mount_graphql_devise_for method on your routes file.
 (called from new at /application/app/graphql/application_schema.rb:18)
2021-12-27T09:39:17.519Z pid=16097 tid=i71 WARN: DEPRECATION WARNING: `confirm_account` is deprecated and will be removed in a future version of this gem.
use the new confirmation flow as it does not require this query anymore

You can supress this message by skipping `confirm_account` on your ResourceLoader or the
mount_graphql_devise_for method on your routes file.
 (called from new at /application/app/graphql/application_schema.rb:18)
2021-12-27T09:39:17.519Z pid=16097 tid=i71 WARN: DEPRECATION WARNING: `check_password_token` is deprecated and will be removed in a future version of this gem.
use the new password reset flow as it does not require this query anymore

You can supress this message by skipping `check_password_token` on your ResourceLoader or the
mount_graphql_devise_for method on your routes file.
 (called from new at /application/app/graphql/application_schema.rb:18)
```

**Comment by 00dav00** [comment]
Hi @wolak88 this is the expected behavior, please notice some operations were replaced (for example `sign_up` is now `register`). Here you have [a list of the currently supported operations](https://github.com/graphql-devise/graphql_devise#available-operations), you can avoid the warning messages by using the new operation names instead of the deprecated ones.

**Comment by wolak88** [comment]
@00dav00 
So this is where I get confused, names of mutations inside gem haven't changed? 
Now there is a discrepancy between operation name and mutation name e.g. `registration` and `GraphqlDevise::Mutations::SignUp`?

**Comment by 00dav00** [comment]
Hi @wolak88, I think this has been updated in the latest version of the gem, as you can see there is no `sign up` file [in the mutations directory](https://github.com/graphql-devise/graphql_devise/tree/master/lib/graphql_devise/mutations).

About `the warning is there even if I don't use those in ResourceLoader` I haven't experienced this myself, but I think one of these can solve it:
- Update the gem to the latest version, where the deprated operations no longer exist
- Add the deprecated operations to the [skip option](https://github.com/graphql-devise/graphql_devise#mounting-operations-in-an-existing-schema) when defining the operations

Could you let us know if that solved you problem please?

**Comment by wolak88** [comment]
Yeah @00dav00 I was confused as I was looking at tagged(0.17.1) version code instead of master and skip option helped for the sidekiq warnings, thanks!

**Comment by wolak88** [comment]
Just one more small question @00dav00 with the deprecation of `update_password` mutation the only flow to change the password is: `sendPasswordResetWithToken -> open email -> click link -> go to screen in app where you put in new password -> updatePasswordWithToken from email`

**Comment by 00dav00** [comment]
Yes @wolak88 that is the flow the gem is planning to keep in the long run. I think you can keep the previous flow as custom mutation if you want to use it for your project.
