### ISSUE TITLE
Dont change dependencies in 0.18.2 version

### ISSUE THREAD

**Issue by DerekSmits** [graphql-devise/graphql_devise#221]
In 0.18.2 version, due to change log adding supporting of GQL 2.0. but while adding it to gemfile i caught an error:

**graphql_devise (>= 0.18.2) was resolved to 0.18.2, which depends on
      graphql (< 1.14.0, >= 1.8)**

**Comment by mcelicalderon** [comment]
@DerekSmits closing this one as no additional feedback was received. Feel free to reopen if you still think there's something we should look into.
