### ISSUE TITLE
Support for ruby-graphql v2

### ISSUE THREAD

**Issue by mengqing** [graphql-devise/graphql_devise#228]
Any timeframe on when to support ruby-graphql v2?

**Comment by mcelicalderon** [comment]
@mengqing I started https://github.com/graphql-devise/graphql_devise/pull/222 months ago but we haven't been able to follow through. I see the importance of supporting V2. I'll try to get it done I August, not sure I'll be able to make it before July ends. Sorry about that

**Comment by mcelicalderon** [comment]
@mengqing initial working implementation in https://github.com/graphql-devise/graphql_devise/pull/222

I hope we can merge and release this soon. This won't be a major release, simply a minor one, so `v0.19`.

Thank you for your patience everyone! And sorry this took so long

**Comment by mengqing** [comment]
@mcelicalderon Thanks for the hard work!! Awesome work!!
