### ISSUE TITLE
Mount only necessary operations in existing schema. 

### ISSUE THREAD

**Issue by mateuszbialowas** [graphql-devise/graphql_devise#239]
### Question

```ruby
  use GraphqlDevise::SchemaPlugin.new(
    query: Types::QueryType,
    mutation: Types::MutationType,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new(Clinic, { skip: %i[update_password_with_token
                                                           send_password_reset_with_token
                                                           resend_confirmation_with_token
                                                           confirm_registration_with_token] })
    ],
    authenticate_default: false
  )
  ```
  In docs I found only options to skip load resources for listed operations. Can I prevent mounting send_password_reset_with_token at all? I don't want the mutation `send_password_reset_with_token` to be available in my mutations. Can I do this?

**Comment by mcelicalderon** [comment]
Hey, @mateuszbialowas! You sure can. Take a look at the available options you can pass to the resource mounter in https://github.com/graphql-devise/graphql_devise#available-mount-options

You can specify the `only` or `skip` option to get only the mutations you want. Let me know if that worked

**Comment by mcelicalderon** [comment]
I see in your example that you are actually using skip. Is that not working? Could you provide a sample repository where you can observe this behavior?

**Comment by mateuszbialowas** [comment]
@mcelicalderon When you said that everything should be fine, I restarted my computer and it began working. Thank you very much.
