### ISSUE TITLE
A custom issue template for discussion?

### ISSUE THREAD

**Issue by aarona** [graphql-devise/graphql_devise#25]
It would be great if you added a custom issue template so that if someone has a question or would like to discuss the project, we could do that in a centralized place. Create react app has a "Question" template which you can see here: https://github.com/facebook/create-react-app/issues/new/choose

**Comment by aarona** [comment]
You guys haven't addressed this. Do you think we don't need it? I feel like it might be a way to ask questions about what you would like added to the documentation or feature requests - some way to ask a question without it being considered an issue.

**Comment by 00dav00** [comment]
Hey @aarona this seems like a near feature to add, I think we can add it in the near future and I will keep this open to don't forget about it. Thanks for the suggestion!
