### ISSUE TITLE
Support graphql v2.1

### ISSUE THREAD

**Issue by bbenno** [graphql-devise/graphql_devise#256]
### What is the problem the enhancement will solve?

[`graphql`](https://github.com/rmosolgo/graphql-ruby) just released version 2.1.0.
Upgrading to this version results in downgrading `graphql_devise` to v0.11.4.

### Describe the solution you have in mind

Updating [dependencies](https://github.com/graphql-devise/graphql_devise/blob/ba5f275bb8167ce0364fe6884050647b748c2b68/graphql_devise.gemspec#L31)

**Comment by mcelicalderon** [comment]
Thank you for the report, @bbenno! Unless there's some incompatibility with the new version, this should be a very quick fix that I can ship today as a new version

**Comment by bbenno** [comment]
@mcelicalderon thanks for the super quick solution.

**Comment by mcelicalderon** [comment]
No problem, @bbenno!

**Comment by mcelicalderon** [comment]
[v1.3.0](https://rubygems.org/gems/graphql_devise/versions/1.3.0) has been published in ruby gems adding support for graphql 2.1
