### ISSUE TITLE
Add ability to customize raise_user_error_list method

### ISSUE THREAD

**Issue by vitaliiorlov** [graphql-devise/graphql_devise#262]
### What is the problem the enhancement will solve?

Our project has a strict structure of errors with custom GraphQL error classes.
And there is no possibility to customize the error structure in this gem.

### Describe the solution you have in mind

You raise this error like this:
```ruby
def raise_user_error_list(message, errors:)
  raise DetailedUserError.new(message, errors: errors)
end

raise_user_error_list(
  I18n.t('graphql_devise.passwords.update_password_error'),
  errors: resource.errors.full_messages
)
```

It would be great to have full control of this process. I would like to specify my own `DetailedUserError` class for this and also not to pass `resource.errors.full_messages` as an argument, I need a more detailed object, for example at least `resource.errors` or better you could change the logic in such way I would have to define some proc which will be passed to the `raise_user_error_list` method:
```ruby
def raise_user_error_list(message, errors:)
  error_klass_name = gem_config.detailed_user_error_class_name.presence || "DetailedUserError"
  error_obj = errors.is_a?(Proc) ? instance_exec(errors) : errors # `instance_exec(errors)` to execute the Proc in the current context or `errors.call` if it's a Proc

  raise error_klass_name.constantize.new(message, errors: error_obj)
end
```

I hope you understand the issue and looking forward to your answer and hope this suggestion will be implemented.
Thanks, guys for your awesome work!

**Comment by mcelicalderon** [comment]
Thank you for your report, @vitaliiorlov! We'll take a look into this shortly. As usual, you are welcome to propose a change if you had a particular implementation in place before we get a chance to look into this :) as long as it's generic and users can opt-in to this new behavior rather than having a breaking change

**Comment by vitaliiorlov** [comment]
@mcelicalderon thanks for your reply. Currently, I don't have any implementation of this. If I will, I will create a PR.

**Comment by mcelicalderon** [comment]
Taking a quick look, I think we should provide a way for users to specify a base mutation from which all mutation in this gem will inherit from. That way you could override the methods that raise errors in that base mutation class that you provide. This will also allow other type of customizations like setting argument classes and other things you can do at the mutation level

**Comment by mcelicalderon** [comment]
@vitaliiorlov are you mounting this gem in your existing schema or are you using the separate route approach?

**Comment by vitaliiorlov** [comment]
@mcelicalderon sounds good. But it won't solve my problem at all because you are already passing `record.errors.full_messages` to the `raise_user_error_list` method. If you could change this behavior by passing `record.errors` to the `raise_user_error_list` and then inside the method call `errors.full_messages` then it could solve my problem if I override your `raise_user_error_list` method in my base mutation class if you allow this as you mentioned above.

> @vitaliiorlov are you mounting this gem in your existing schema or are you using the separate route approach?

I mount it in the existing schema.

**Comment by mcelicalderon** [comment]
> If you could change this behavior by passing record.errors to the raise_user_error_list and then inside the method call errors.full_messages then it could solve my problem

That makes sense. We can do that too

**Comment by mcelicalderon** [comment]
@vitaliiorlov I have opened https://github.com/graphql-devise/graphql_devise/pull/263 which I think is enough to accomplish what you are trying to do, but let me know if it doesn't. 

With that simple change, you can write your own mutation that implements a different `raise_user_error_list(message, resource: resource)`. So something like this:

1. Write your own custom mutation that inherits the one you are interested in from this gem. We do the same on our specs in https://github.com/graphql-devise/graphql_devise/blob/b1435baabc1356fcc2c463a2b1f37a38e89abaae/spec/dummy/app/graphql/mutations/register_confirmed_user.rb
2. Then, when using the plugin in your existing schema, you can specify this new mutation in your schema loader as specified in the docs https://github.com/graphql-devise/graphql_devise#available-mount-options using the `operations` option.

Define a custom mutation with your custom method definition
```ruby
# app/graphql/mutations/custom_register.rb
module Mutation
  class CustomRegister < GraphqlDevise::Mutations::Register
    private
    
    def raise_user_error_list(message, resource:)
      # your custom behavior, resource will be an active record instance if you are using active record
    end
  end
end
```
  
specify the mutation for the operation you wish to change
```ruby
class AppSchema < GraphQL::Schema
  use GraphqlDevise::SchemaPlugin.new(
    query:                Types::QueryType,
    mutation:             Types::MutationType,
    resource_loaders:     [
      GraphqlDevise::ResourceLoader.new(
        User,
        only: [:register],
        operations: {
          register: Mutations::CustomRegister
        },
      )
    ]
  )

  mutation(Types::MutationType)
  query(Types::QueryType)
end
```

Let me know if this works for you and I can release a new version of the gem that includes https://github.com/graphql-devise/graphql_devise/pull/263 so you can do what I have described here.

I think that doing something like what I described in https://github.com/graphql-devise/graphql_devise/issues/262#issuecomment-1777621294 might be unnecessary if we can already do something similar by specifying the actual mutation and not a base mutation that all other will inherit from.

**Comment by mcelicalderon** [comment]
@vitaliiorlov yes, this behavior is expected. Whenever you specify a custom mutation, we do not make any changes to it compared to when you don't specify one and we set the `authenticatable` field automatically. For you use case, please simply add the missing field to your custom mutation. For reference, this is how the gem sets that field 

https://github.com/graphql-devise/graphql_devise/blob/b1435baabc1356fcc2c463a2b1f37a38e89abaae/lib/graphql_devise/mount_method/operation_preparers/mutation_field_setter.rb#L14

**Comment by vitaliiorlov** [comment]
@mcelicalderon got it. Waiting for merging. Thanks a lot!

**Comment by mcelicalderon** [comment]
No problem, @vitaliiorlov! v1.4.0 has been released with this changes
