### ISSUE TITLE
Uninitialized constant `GraphqlDevise::SchemaPlugin` After trying to mount `graphql_devise` in my schema

### ISSUE THREAD

**Issue by Forison** [graphql-devise/graphql_devise#270]
Hello team

I am currently working with `graphql_devise`. I have been attempting to mount `graphql_devise` in my schema. According to the documentation, I can do that by placing this code inside my schema like this
```
class ProjectGesSchema < GraphQL::Schema
  use GraphqlDevise::SchemaPlugin.new(
    query: Types::QueryType,
    mutation: Types::MutationType,
    public_introspection: true,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new(User,
                                        only: %i[register])
    ]
  )
```
For some reason I get uninitialized constant `GraphqlDevise::SchemaPlugin`

Do I have to define this class on my own??

Please does anyone knows why this is occurring?

**Comment by 00dav00** [comment]
Hi @Forison, did you execute the [install command](https://github.com/graphql-devise/graphql_devise?tab=readme-ov-file#installation)? What are the steps that you have followed so far to include the gem in your project?

**Comment by Forison** [comment]
Hello @00dav00,
Thanks for the feedback
I executed the command as described in the docs. For clarification here are the steps I took after creating my rails project

- bundle add 'grapql_devise'

- rails generate graphql_devise:install User --mount mySchemaName

- Then I visited my schema and inserted the from the doc

```
 use GraphqlDevise::SchemaPlugin.new(
    query: Types::QueryType,
    mutation: Types::MutationType,
    public_introspection: true,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new(User,
                                        only: %i[register])
    ]
```
This resulted in `uninitialized constant GraphqlDevise::SchemaPlugin`

**Comment by Forison** [comment]
Hello @00dav00 and any other person who runs into this same issue,
To resolve this I had to downgrade graphql to version 2.2 and upgrade graphql_devise to version 1.4.0. 
This is because graphql version 2.3 is compatible with 0.11.4 only

**Comment by 00dav00** [comment]
Thanks for posting the solution @Forison !

**Comment by mcelicalderon** [comment]
@00dav00 I think we should yank gem versions that were published before we introduced strict version requirements for dependencies. This has happened before
