### ISSUE TITLE
Schema.tracer Deprecation Warning

### ISSUE THREAD

**Issue by t2** [graphql-devise/graphql_devise#273]
https://github.com/graphql-devise/graphql_devise/blob/febac4fc5f501b59859419e25d36dd9abf7e645a/lib/graphql_devise/schema_plugin.rb#L22C7-L22C37

Schema.tracer(#<GraphqlDevise::SchemaPlugin:0x00007f7c7e3f7710 @query=Types::QueryType, @mutation=Types::MutationType, @resource_loaders=[#<GraphqlDevise::ResourceLoader:0x00007f7c7e3f78c8 @resource=User(id: integer, created_at: datetime, updated_at: datetime, account_id: integer, role: integer, name: string, title: string, pronouns: string, phone: string, email: string, encrypted_password: string, time_zone: string, reset_password_token: string, reset_password_sent_at: datetime, remember_created_at: datetime, sign_in_count: integer, current_sign_in_at: datetime, last_sign_in_at: datetime, current_sign_in_ip: string, last_sign_in_ip: string, confirmation_token: string, confirmed_at: datetime, confirmation_sent_at: datetime, unconfirmed_email: string, invitation_token: string, invitation_created_at: datetime, invitation_sent_at: datetime, invitation_accepted_at: datetime, invitation_limit: integer, invited_by_type: string, invited_by_id: integer, invitations_count: integer, slug: string, failed_attempts: integer, locked_at: datetime, unlock_token: string, provider: string, uid: string, tokens: json, sex: integer, bio: text, office_phone: string, referral_code: string, preferences: jsonb, tag_list: , skill_list: , interest_list: ), @options={:only=>[:login, :logout, :register, :send_password_reset_with_token], :operations=>{:login=>Mutations::Auth::Login, :register=>Mutations::Auth::Register}}, @routing=false, @default_operations={:login=>{:klass=>GraphqlDevise::Mutations::Login, :authenticatable=>true}, :logout=>{:klass=>GraphqlDevise::Mutations::Logout, :authenticatable=>true}, :register=>{:klass=>GraphqlDevise::Mutations::Register, :authenticatable=>true}, :update_password_with_token=>{:klass=>GraphqlDevise::Mutations::UpdatePasswordWithToken, :authenticatable=>true}, :send_password_reset_with_token=>{:klass=>GraphqlDevise::Mutations::SendPasswordResetWithToken, :authenticatable=>false}, :resend_confirmation_with_token=>{:klass=>GraphqlDevise::Mutations::ResendConfirmationWithToken, :authenticatable=>false}, :confirm_registration_with_token=>{:klass=>GraphqlDevise::Mutations::ConfirmRegistrationWithToken, :authenticatable=>true}}>], @authenticate_default=false, @public_introspection=true, @unauthenticated_proc=#<Proc:0x00007f7c7e8d7938 /app/vendor/bundle/ruby/3.1.0/gems/graphql_devise-1.5.0/lib/graphql_devise/schema_plugin.rb:7 (lambda)>>)` is deprecated; use module-based `trace_with` instead. See: https://graphql-ruby.org/queries/tracing.html
  /app/vendor/bundle/ruby/3.1.0/gems/graphql_devise-1.5.0/lib/graphql_devise/schema_plugin.rb:22:in `use'

**Comment by mcelicalderon** [comment]
Thank you for the report, @t2! We'll look into this, looks like a small change to remove the deprecated code 🤞

**Comment by maxschridde1494** [comment]
any updates on this? eta for fix?

**Comment by maxschridde1494** [comment]
gentle nudge here. Is this actively getting worked on or is an assist needed?

**Comment by mcelicalderon** [comment]
Hey, @maxschridde1494! Sorry we haven't had a chance to work on this. It's hard to find time to work on this at the moment. Help is always welcome! So if you want to give it a try I'd be happy to review a PR from you 🙌
