### ISSUE TITLE
More meaningful error messages

### ISSUE THREAD

**Issue by celsoMartins** [graphql-devise/graphql_devise#275]
Hi.

In the register mutation, I need to be able to inform my users if they are trying to register a duplicated email address or nickname, but I'm struggling with the error structure of the gem, sending only "User couldn't be registered".

I've checked some issues here, especially this: https://github.imc.re/graphql-devise/graphql_devise/issues/166

But none helped.

Do you know how I can do that?

Also, we use custom error codes in a field status_message, but with graphql_devise I can't do that.

I struggled and failed to get the "extensions" in Apollo, as I do in my specs, but I did not succeed.

`expect(result.dig('errors', 0, 'extensions', 'detailed_errors')).to eq ['Password is too short (minimum is 8 characters)']`

Is there a way to do that? It is a fundamental feature.

Thank you.

**Comment by celsoMartins** [comment]
I was able to solve this by intercepting the exception and controlling what it was sending to react.

But it would be simpler if we could access the resource when we are overriding the "register" mutation.

It wasn't easy to find that "to_h" in the gem files.

```
rescue GraphqlDevise::DetailedUserError => e
  { status_message: 'FAIL', errors_details: e.to_h[:extensions][:detailed_errors].join(', ') }
end
```

Thank you anyway. Now I can send meaningful feedback to my users.

**Comment by mcelicalderon** [comment]
Hey, @celsoMartins. I'm glad you were able to resolve it. Another way would be to override the `raise_user_error_list` method in your mutation, but perhaps your approach is more appropriate as you won't depend on the private interface of the gem.

I agree we should refactor mutations into something more extensible to allow any type of extension while preserving the core parts of the mutation's logic. Do you have suggestions? Happy to review a proposal if you have one for your current implementation. This would be simpler than implementing something like what we discussed in https://github.imc.re/graphql-devise/graphql_devise/issues/166
