### ISSUE TITLE
When using React, how do you solve the problem if needing two ApolloClients?

### ISSUE THREAD

**Issue by aarona** [graphql-devise/graphql_devise#29]
I'm starting to build out a react app and I'm coming across what seems like a potentially big road block. Having two `ApolloClient` components. Do you guys just nest them in your `index.{tsx,jsx,js}` file like so:

```jsx
<ApolloProvider client={client}>
    <App/>
</ApolloProvider>
```

and then when you want to use authentication end point (inside `App` component):

```jsx
<ApolloProvider client={authClient}>
  <Login />
</ApolloProvider>
```

what if you need to use both in the same component? I've been looking into this and there is apparently a solution called `<ApolloMulipleClientsProvider>` but all it does it what I think I should be doing in my above example. I know we have a dummy app in the spec directory for server side testing but as I'm working on a simple example with a React front end, it looks like there could be issues and that seems to be the whole point, right?

**Comment by mcelicalderon** [comment]
Hey @aarona , so I'm not a react developer but there seem to be a couple of ways to accomplish that. As the API is client independent I don't think it should be an issue of this gem. For example this is how you have multiple graphql schemas in angular https://www.apollographql.com/docs/angular/features/multiple-clients/

For react it looks like it was also implemented from what I read on this PR https://github.com/apollographql/react-apollo/pull/729

This one might also be useful https://github.com/apollographql/react-apollo/issues/1588

**Comment by aarona** [comment]
Yeah not an issue that you guys need to solve. See my other "issue" about wanting a way to pose questions like some other GH repos/libraries allow. I've been hearing lately that people are actually moving away from SO and are starting to post questions to the libraries they are having issues with - not because they are broken (although that could be the case) - but because they might be asking that gem/js lib/etc community a general question. I believe there might be a "question" tag that you can auto-apply when you're setting up the custom issues so they get filtered out of issues related to the library.

When the question gets answered, they questioner or someone moderating the library can close the question like you would an issue.
