### ISSUE TITLE
Potential naming convention violation found

### ISSUE THREAD

**Issue by aarona** [graphql-devise/graphql_devise#31]
per @mcelicalderon 's request, I'm taking  a stab at a `ResendConfirmation` mutation. I noticed in the `routes.rb` file an inconsistency that I think should be fixed before this gem gets popular.

Consider the following code from `routes.rb`:

```ruby
default_mutations = {
  login:               GraphqlDevise::Mutations::Login,
  logout:              GraphqlDevise::Mutations::Logout,
  sign_up:             GraphqlDevise::Mutations::SignUp,
  update_password:     GraphqlDevise::Mutations::UpdatePassword,
  send_reset_password: GraphqlDevise::Mutations::SendPasswordReset,
  resend_confirmation: GraphqlDevise::Mutations::ResendConfirmation
}.freeze
```

I believe that the mutation class should be renamed from `SendPasswordReset` to `SendResetPassword`. The other option is to change the key from `send_reset_password:` to `send_password_reset:` but I think that would be a breaking change (which is why I said we should fix this immediately) but also I like verb `send` or in my case `resend` to be in the front as a convention and renaming the mutation class I think would prevent a breaking fix.

Let me know what you guys think. Also, if I have any other questions like this, should I post them here as issues? I think adding a custom question issue template would be useful. (see my other issue that I posted last week.)

**Comment by mcelicalderon** [comment]
mmm you are right, I'll change it. I think opening issues with your concerns here is fine.
