### ISSUE TITLE
Modify confirmation mailer

### ISSUE THREAD

**Issue by Gakamine** [graphql-devise/graphql_devise#37]
Hello,
I'd like to change the format of the confirmation URL link in the mail template. My current URL format is:
`http://www.mydomain.com/graphql/auth?query=query($token:String!,$redirectUrl:String!){userConfirmAccount(confirmationToken:$token,redirectUrl:$redirectUrl){email}}&variables[redir$tokenectUrl]=<redirectUrl>&variables[token]=<token>`
and I wish to replace it by 
`https://mydomain.com/auth/token=<token>&action=ConfirmEmail`.
In the "confirmation_instructions.html.erb", I noticed this line which is actually generating the link to confirm the email:
`<%= link_to t('.confirm_account_link'), url_for(controller: 'graphql_devise/graphql', action: :auth, **confirmation_query(resource_name: @resource.class.to_s, redirect_url: message['redirect-url'], token: @token)) %>`
How do I have to change this line to get the URL format I want ?

Thank you !

**Comment by mcelicalderon** [comment]
Hey @Gakamine, the existing format in the template has that format as it has a GraphQL query encoded as a url param. So clicking on that will actually hit one of the mounted queries provided by this gem. If for whatever reason you want to change it, you could just override the template in your app by creating this file in your rails project `app/views/graphql_devise/mailer/confirmation_instructions.html.erb` ans replace the `link_to` line with what you want.

```ruby
<%= link_to 'link text', url_for(controller: '<your_controller>', action: :<your_controller_method>, token: @token, action: 'ConfirmEmail') %>
```
I think that will generate what you want, I do recommend using url_for so rails gets the url for you based on how you have mounted it in your `config/routes.rb` file

**Comment by aarona** [comment]
This is a good question that I also had because I plan on implementing this also.
