### ISSUE TITLE
Mutation documentation is missing in the README.md

### ISSUE THREAD

**Issue by aarona** [graphql-devise/graphql_devise#43]
Not sure how it happened, but the mutation documentation I added got removed/reverted and all that's left is from my last PR for the `ResendConfirmation` enhancement. That documentation update had some grammar errors that are back also. I checked to see if my PR reflected these changes but it doesn't. However, it looks like my PR broke this and I think this was my fault somehow. I shouldn't have rebased my feature branch when you guys updated master. I'll know not to do that again.

Also the the github custom issue templates were removed. I can resubmit my documentation changes as a new PR and I can add the github custom issue templates as a separate PR unless @00dav00 wants to do that.

![image](https://user-images.githubusercontent.com/176590/69511771-58a25a00-0ef6-11ea-87e0-61b7a0d1474a.png)

**Comment by mcelicalderon** [comment]
Very weird, taking a look now. Weird the PR didn't show that

**Comment by mcelicalderon** [comment]
Already reverted the relevant changes @aarona , not sure how we missed this on the PR, but I think I have seen it before, github has problems refreshing the changes view when rebasing and merges happen. Closing as it has been resolved in master. Try to make your commit history cleaner next time to avoid this type of issue, merging master into your branch is always a safer thing to do as it doesn't re-write history like a rebase (destructive).

**Comment by mcelicalderon** [comment]
We are not alone, looks like it is a know github issue https://stackoverflow.com/a/26986320/1755141

**Comment by aarona** [comment]
Ah! Ok I thought I was going insane. Yeah I learned a lot about working with teams at git with that PR. Thanks again for asking me to contribute to this project. I've really enjoyed it!
