### ISSUE TITLE
authenticable vs authenticatable

### ISSUE THREAD

**Issue by aarona** [graphql-devise/graphql_devise#45]
### Question
Should we have a documentation/code naming standard for authenticable/authenticatable? 

authenticatable has 14 results with only one in the documentation.
authenticable has 38 results with five in the documentation.

I did some googling and these mean the same thing with authenticable referencing authenticatable as being an alternate form of it (meaning authenticatable is the more standard form of this word). See:
https://en.wiktionary.org/wiki/authenticable

What's more is that Devise itself addresses this issue and the decision was to conform to authenticatable:

https://github.com/plataformatec/devise/issues/4157

If we were to move to authenticatable this would be a breaking change so it would probably be good to do it as soon as possible before this library gets really popular.

**Comment by mcelicalderon** [comment]
You are right. @00dav00 what do you think? We do the change now ASAP?
