### ISSUE TITLE
Works with Rails 6 api only app?

### ISSUE THREAD

**Issue by kockok** [graphql-devise/graphql_devise#51]
### Question

I am getting this response from graphiql-rails after sending userSignUp mutation.

```
  "status": 500,
  "error": "Internal Server Error",
  "exception": "#<ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true>",
```

**Comment by mcelicalderon** [comment]
Looks like you might need to provide a default url for your environment. Take a look at this line on the dummy app https://github.com/graphql-devise/graphql_devise/blob/3310c332bcf5c82600bcfb3d7cc9a99b3cb59f2b/spec/dummy/config/environments/test.rb#L38
Make sure you set that for each environment with the correct value. 

If that wasn't it, please provide additional details on the error.

**Comment by kockok** [comment]
It seems that a URL path is required whilst there's no such a path in rails api only app.
![Screenshot 2019-12-23 at 10 39 16 AM](https://user-images.githubusercontent.com/232541/71332369-dfd40380-2570-11ea-9a58-14b33efe00c3.png)

**Comment by aarona** [comment]
A side note: Look into MailCatcher when developing your application. You can find more about that from DTA's documentation. It acts as a local mail server so you can test that your emails get "sent".
