### ISSUE TITLE
Integration with graphql ruby gem

### ISSUE THREAD

**Issue by kockok** [graphql-devise/graphql_devise#56]
### Question
I have to use the graphiql interface and for the time being, I have to switch between the `/auth` and `/graphql` route for graphiql.

So, I would like to ask if they both can be integrated as one single path or something.
![Screenshot 2019-12-27 at 6 32 41 PM](https://user-images.githubusercontent.com/232541/71514019-d384d900-28d7-11ea-8363-f480201caf41.png)

Thanks.

**Comment by Gakamine** [comment]
Good question, it would be easier for me too.

**Comment by mcelicalderon** [comment]
So, from the beginning we had to decide for having a separate endpoint for your graphql schema and the auth schema. The reason, some mutations and queries on the auth schema require for the controller not to authenticate. I don't think implementing a way to just add queries to your main schema would be nice as we would have to look into the sent query to decide whether to authenticate or not. But for graphiql I just have two paths, one for my main schema and another for the auth schema. Like this

```ruby
unless Rails.env.production?
  post '/api/v1/graphql_dev', to: 'api/v1/graphql#execute_dev'
  mount GraphiQL::Rails::Engine, at: '/api/v1/graphiql', graphql_path: '/api/v1/graphql_dev'
end

mount_graphql_devise_for(
  'User',
  at: 'api/v1/graphql_auth',
)
unless Rails.env.production?
  mount GraphiQL::Rails::Engine, at: '/api/v1/graphiql_auth', graphql_path: '/api/v1/graphql_auth', as: :graphql_auth
end
