### ISSUE TITLE
Could not find generator 'graphql_devise:install'

### ISSUE THREAD

**Issue by Gakamine** [graphql-devise/graphql_devise#57]
Hello,
I already posted here but I'm working on a second project and I'd like to implement this gem in it.
I'm having troubles to run this gem generator. I have installed the gem and bundled (the gem appear in the output) but every time I try to run the generator I'm having this error message:
`Could not find generator 'graphql_devise:install'`
![Gem file and terminal](https://i.postimg.cc/YCYRf1kh/unknown.png)
I'm pretty sure it's a dumb mistake from me but I can't figure out what it is.. Any ideas ?
If you want to check the code it's available here: https://github.com/Gakamine/PriviChat-Server
Thank you.

**Comment by mcelicalderon** [comment]
Hey @Gakamine, so I looked into your code and looks like you are using `v0.3.0` of this gem [here](https://github.com/Gakamine/PriviChat-Server/blob/d300f24acd362fbd671b917ca3c7922f39218277/Gemfile.lock#L96) and the generators were introduced in `v0.5.0` please try using the latest version which now is `v0.9.1`. Closing this one as I tested the latest version does have the generator, but let me know if it still doesn't work for you.

**Comment by Gakamine** [comment]
Working far better. I'm just a little curious why it installed an outdated version..
Thank you !
