### ISSUE TITLE
wrongly submitted.

### ISSUE THREAD

**Issue by kockok** [graphql-devise/graphql_devise#58]
wrongly submitted.

**Comment by mcelicalderon** [comment]
Not completely sure what you mean. The default type for `authenticatable` has  only email as is the only field required by devise. Look [here](https://github.com/graphql-devise/graphql_devise/blob/4749c34aba02baebb511b6608dc1b2edee3d4729/app/graphql/graphql_devise/types/authenticatable_type.rb#L4). But of course you can change that type and use anyone you want, your own custom type. Looks at this snippet from the readme on how to specify your own graphql type when mounting the gem in the routes file.

```ruby
# config/routes.rb

Rails.application.routes.draw do
  mount_graphql_devise_for(
    'User',
    at: 'api/v1',
    authenticatable_type: Types::MyCustomUserType
  )
end
```

Your Rails app can have any type you declare, in this case we called it `Types::MyCustomUserType`. That type can have any field you want on the `User` model. Of course you have to add the columns in the DB too. Take a look at our specs that use a rails project to illustrate this https://github.com/graphql-devise/graphql_devise/blob/4749c34aba02baebb511b6608dc1b2edee3d4729/spec/dummy/app/graphql/types/user_type.rb

Let me know if I understood your question correctly ;)
