### ISSUE TITLE
Gem isn't found in rubygems.org

### ISSUE THREAD

**Issue by aarona** [graphql-devise/graphql_devise#6]
Trying to run `bundle` with this gem in the `Gemfile`. Get the following error:

```
$> bundle
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'graphql_devise' in any of the gem sources listed in your Gemfile.

```

Tried installing it like so also:

```
$> gem install graphql_devise
ERROR:  Could not find a valid gem 'graphql_devise' (>= 0) in any repository
```
I know I can reference it directly on github but maybe change the documentation to reflect this until its published on rubygems.

**Comment by mcelicalderon** [comment]
We have not released the gem yet (first version not complete yet), so it is not available at RubyGems. In the mean time if you want to try out whatever we have, you can clone this repository and point to it in you gemfile like this
```ruby
gem 'graphql_devise', path: '<your_path>/graphql_devise'
```
Also, as we don't have any docs yet, you can refer to [this dummy app](https://github.com/graphql-device/graphql_devise/tree/master/spec/dummy) we use for testing to see how to use it.

We are giving it all the available time we have to this gem, so please bear with us while we release a first version ;)

**Comment by aarona** [comment]
I'm very patient. Don't forget I was the guy you talked to on SO last week or so. I'm opening to help contribute in anyway whether it be documentation or code or what have you. I'll clone it for now and get familiar with the code base and if you're open to pull requests, let me know.

**Comment by mcelicalderon** [comment]
Thank you, and we will need help in the near future. Also, I already pushed the gem to rubygems so you should be able to download just by adding to the gemfile as usual.

**Comment by aarona** [comment]
Awesome! I just noticed that before coming here. Do you guys have a slack server? If so, should I email you (in case you dont want that information public) I've installed the gem along with `devise` and `graphql` but there doesn't seem to be any references to the `types`, `queries` or `mutations` when I hit the graphql end point. Do you guys have any quick and dirty setup documentation at the moment that I can get my hands on so I can play around with what you have for now?

**Comment by mcelicalderon** [comment]
Closing this one as the gem is already available in rubygems and we are about to release the first functional version (probably tomorrow).
