### ISSUE TITLE
Routes mount_graphql_devise_for with module not work

### ISSUE THREAD

**Issue by dwthien** [graphql-devise/graphql_devise#69]
### Describe the bug

I used mount_graphql_devise_for 'User::Customer' with struct models/user/customer. The error with message: :uninitialized constant UserCustomer

I tested with mount_devise_token_auth_for 'User::Customer' and it worked with devise_token_auth.

ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
rails (6.0.2.1)

**Comment by mcelicalderon** [comment]
Hey @dwthien, thank you for the report! I will look into this as soon as possible, but at least a backtrace from the error would help a lot identifying the problem.

**Comment by dwthien** [comment]
Hi @mcelicalderon , 
thank you for the reply, this is the best gem for me.

if I move customer come out parent folder, it worked, but I want to use the module to group the use, I attached some pictures in here about the error:
![image](https://user-images.githubusercontent.com/25741737/77226735-18ee3500-6bad-11ea-8d8e-973da5716f09.png)
![image](https://user-images.githubusercontent.com/25741737/77226741-36bb9a00-6bad-11ea-81a5-1883a23fca9a.png)

**Comment by mcelicalderon** [comment]
Thank you @dwthien, that is really helpful. I have identified the error. Will publish a fix as soon as possible

**Comment by mcelicalderon** [comment]
`v0.10.1` was released and fixes this bug @dwthien ;)

**Comment by dwthien** [comment]
thank a lot, actually, I pull code from your branch, haha
now I will pull again, once thank you very much for your support  @mcelicalderon
