### ISSUE TITLE
Could not find generator 'graphql_devise:install'. Maybe you meant "graphql:install"?

### ISSUE THREAD

**Issue by Dujota** [graphql-devise/graphql_devise#77]
gems: 
```
ruby '2.7.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'

gem "devise", "~> 4.7"
gem "graphql_devise", "~> 0.10.1"

gem "graphql", "~> 1.10"
```

following the gem's install instructions:

i do `bundle add graphql_devise`

then i run 

`rails g graphql_devise:install`

output is : 

```
could not find generator 'graphql_devise:install'. Maybe you meant "graphql:install"?
Run `rails generate --help` for more options.
```

when i run `rails g --help` i also do not see 

Couldn't find anything here to indicate what could be the issue, other than update >0.9 which is not the problem here. 

cheers.

**Comment by mcelicalderon** [comment]
Hey @Dujota thank you for the report. I just tested on a new rails project with the gem version you specified, but unless you provide the `Gemfile.lock` file I can't know for sure that I used the exact same version. Actually, if you could provide both `Gemfile` and `Gemfile.lock` together in a gist, that would be great. I also tried with ruby 2.7.0.
Also, running `rails` directly as you example show is usually not a good practice as you won't necessarily run the rails version the project is supposed to run, it depends on your local environment. Instead, you should run `bundle exec rails g graphql_devise:install` or the included binstub (which I usually use) `bin/rails g graphql_devise:install` on the root of the rails app. Both versions will run gems on the version specified on your Gemfile. Also make sure that bundle install is successful.

Let me know if that did the trick

**Comment by Dujota** [comment]
@mcelicalderon thank you for the quick response 👍 

`bundle install` is successful 
```
Using graphql 1.10.5
Using graphql_devise 0.10.1
Using jbuilder 2.10.0
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.1
Using ruby_dep 1.5.0
Using listen 3.1.5
Using pg 1.2.3
Using pry 0.13.0
Using puma 4.3.3
Using rack-proxy 0.6.5
Using rspec-support 3.9.2
Using rspec-core 3.9.1
Using rspec-expectations 3.9.1
Using rspec-mocks 3.9.1
Using rspec-rails 4.0.0
Using sassc 2.2.1
Using tilt 2.0.10
Using sassc-rails 2.1.2
Using sass-rails 6.0.0
Using spring 2.1.0
Using spring-watcher-listen 2.0.1
Using web-console 4.0.1
Using webpacker 4.2.2
Bundle complete! 20 Gemfile dependencies, 83 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

I ran all 3 `bundle exec rails g graphql_devise:install`  & `bin/rails g graphql_devise:install` plus `rails g graphql_devise` 

they all spit out the same output 
```
Run `rails generate --help` for more options.
```

As requested: 


`Gemfile` :  https://gist.github.com/Dujota/e339b9e6c5325637c95be7d5a590783a

`Gemfile.lock` : https://gist.github.com/Dujota/41b80fd62b963204ba2b50f7619c61c5

**Comment by mcelicalderon** [comment]
Thank you for providing the gists. I have tried those locally using ruby 2.7.0 and I'm still unable to see the same problem. Now we need a way to replicate what you are seeing. If you can provide a public repo with the app causing this issue that'd be great, if not, the next best thing would be any rails app in a repository where you can consistently see this behavior. Only then I will be able to see what might be going on.

**Comment by 00dav00** [comment]
Hey @Dujota , any chance you are using something like `spring`?
Sometimes that needs a restart installing new gems.

**Comment by Dujota** [comment]
@00dav00 hey, good call on `spring` i had to run `spring stop`
