### ISSUE TITLE
Get the Mutations going

### ISSUE THREAD

**Issue by benoitcalin** [graphql-devise/graphql_devise#83]
Hi all,

We are currently trying out this gem for a new project after some weeks of inquiries on GraphQL.

The migration part is not perfectly clear for us, we found some migration files in lib directory but thought it would be generated by the gem. Are we doing something wrong or are we supposed to add the mutations/resolvers manually ?

In case we have to do it manually does anyone has an example repo with this implemented for the User generated by the gem on which we could work ?

Thanks a lot in advance,

Regards, 

Benoit

**Comment by 00dav00** [comment]
Hi @benoitcalin, migrations are directly coming from DTA. They should be installed if you use when you generate the route for the resource using a command like this `rails g graphql_devise:install Admin api/auth` .

The [installation part](https://github.com/graphql-devise/graphql_devise#installation) of the README has more details in what is happening here.

Please let me knwo if you find what you need there :)

**Comment by benoitcalin** [comment]
Thanks a lot you 00dav00, we will try it again tomorrow and keep you updated, we must have done something wrong the several previous times ;)

**Comment by mcelicalderon** [comment]
AS @00dav00 mentioned, install generators should take care of it, and you definitively don't have to add mutations and queries manually, that's all done for you depending of the options you pass to the mount method. Just remember that the entire auth schema this gem generates is mounted in a separate route from your app's actual GQL schema. The [dummy app](https://github.com/graphql-devise/graphql_devise/tree/master/spec/dummy) we use in our specs is a good example on how a real Rails app might look when using the gem.

**Comment by benoitcalin** [comment]
Thanks @mcelicalderon it's clearer for us with your explanations, we were trying to access this mutations for tests through graphiql without understanding that it was mounted somewhere else.

**Comment by mcelicalderon** [comment]
We have some docs updates pending that we will definitively work on soon. We can close this one then as part of that change.
