### ISSUE TITLE
ActionController::InvalidAuthenticityToken for fresh install

### ISSUE THREAD

**Issue by single-stop-rj** [graphql-devise/graphql_devise#90]
### Describe the bug
Im not sure if there is some config item I am missing, but this seems like a localized issue. 

Trying to use the gem results in 

```shell
ActionController::InvalidAuthenticityToken at /auth
===================================================

> ActionController::InvalidAuthenticityToken

actionpack (6.0.3.1) lib/action_controller/metal/request_forgery_protection.rb, line 215
----------------------------------------------------------------------------------------

``` ruby
  210           def initialize(controller)
  211             @controller = controller
  212           end
  213   
  214           def handle_unverified_request
> 215             raise ActionController::InvalidAuthenticityToken
  216           end
  217         end
  218       end
  219   
  220       private
```

my application controller
```ruby 
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # skip_before_action :verify_authenticity_token
  protect_from_forgery with: :exception, prepend: true
end
```

### Steps to reproduce
I installed this from scratch. I also have my own graphql API mounted at /graphql. 
The auth one is the only one throwing the error unless I remove CSRF protection

**Comment by mcelicalderon** [comment]
Hey @single-stop-rj! I see what's going on there. So you are running this API alongside a regular full-stack rails app? If so, do you use standard devise there?

**Comment by single-stop-rj** [comment]
Yes. Thats exactly what I have! 

I also have added the config item 

`config.enable_standard_devise_support = true` in the init file, if that helps.

**Comment by mcelicalderon** [comment]
Ok! So, as described in the Readme file, support for standard devise together with this gem is experimental and I know for a fact that some things might misbehave. But in general, there's usually a way to make it work. But for your main problem, this is the best solution I have found and the one I use (kind of) https://devise-token-auth.gitbook.io/devise-token-auth/faq#another-method-for-using-this-gem-alongside-standard-devise-updated-may-2018

So what happens is that we inherit from devise token auths controller, they inherit from Devise, and Devise inherits from your App's `ApplicationController`. And we can't change that in this gem (maybe in the future). So the gist of the solution is as follows:

Have a naked `ApplicationController` that doesn't protect from forgery or any other thing you might already have on your application controller.
Create a new controller for the full-stack side (mine is called `ApplicationMainController`) than inherits from application controller

`ApplicationMainController < ApplicationController`
Then make every full-stack controller in your app inherit from the new `ApplicationMainController`
. Make ApplicationMainController protect_from_forgery and everything you need for the full-stack app.

And then create another API controller that you probably already have that could go like this:

`ApiController < ApplicationController`

And that should do it, the main thing about this is having `ApplicationController` as plain as possible, specially not protecting from forgery.

I know it works! But let me know if I was unclear about something.

**Comment by single-stop-rj** [comment]
It all makes sense now. Ok. Thank you so much.

**Comment by mcelicalderon** [comment]
Mmm just an additional note @single-stop-rj what I suggested will actually remove forgery_protection from your standard devise controllers, which is not ideal. I'll see what we can do in this gem to not force you to do that.

**Comment by mcelicalderon** [comment]
@single-stop-rj #93 will take care of this, forgery_protection should not be a problem anymore and you don't have to change anything in order to avoid it. But, if you are using regular devise and if you were calling `before_action :authenticate_user!` in your `ApplicationController`, you will still need to change your controller structure as I described before.
