### ISSUE TITLE
ActiveAdmin support

### ISSUE THREAD

**Issue by grdmnt** [graphql-devise/graphql_devise#97]
### Question
Since activeadmin relies on `ApplicationController` the same with this gem, they're going to conflict given that activeadmin uses the standard devise while this gem relies on DTA. Is there a way where we can specify the controller that this gem uses?

**Comment by grdmnt** [comment]
My bad. Saw the recent updates for this gem and updating it to `0.11.4` resolves this issue.

**Comment by mcelicalderon** [comment]
Hey @grdmnt, perhaps you can do something similar to what I described in this issue https://github.com/graphql-devise/graphql_devise/issues/90#issuecomment-631715313

But actually, I'm working on a new version of this gem where we won't inherit from application controller.

**Comment by mcelicalderon** [comment]
Oh, I guess you were having authenticity token issues then. But yes, the issue I shared describes everything related to that. Also, there won't be a need for that after this pr https://github.com/graphql-devise/graphql_devise/pull/96

**Comment by grdmnt** [comment]
Got it! @mcelicalderon. Sorry for the unnecessary issue 😅  Thanks man!
